### ISSUE TITLE
GLPI 0.90.5 - DATA INJECTION 2.4.1

### ISSUE THREAD

**Issue by Juliencpi** [pluginsGLPI/datainjection#10]
Bonjour à tous,
je n'arrive pas à importer un mail via le plugin data Injection par fichier csv. Les autres champs ne posent pas de problème (nom, prénom, téléphone, titre, lieu ..).
J'ai l'impression en y regardant de plus près que le champ "Adresses de messagerie" comprend un booléen d'activation .. comment faire pour qu'il soit pris en compte ?
Merci, bien cordialement

Hello everyone,
I do not import mail data via the plugin Injection by CSV file. The other fields do not pose a problem (name, phone, title, place ..).
I feel in looking more closely as the field "Mail Addresses" includes a Boolean activation .. how can it be addressed?
Thank you, best regards

**Comment by ViTalityGH** [comment]
It is not question. IT IS A BUG!
How to import mail addresses?
