### ISSUE TITLE
Synology nas GLPI "Data injection" plug-in installation error

### ISSUE THREAD

**Issue by hahahasong** [pluginsGLPI/datainjection#101]
I installed glpi on nas and installed the data injection plugin
CSRF Compliant No "No"
How do I fix it?

I do not know when I first installed it.
Please take care

**Comment by trasher** [comment]
Use latest version of the plugin, this should solve that.

**Comment by hahahasong** [comment]
I installed version 2.5.2
![csrf](https://user-images.githubusercontent.com/40617432/41957329-87ccb30e-7a21-11e8-9796-2c0e422c1ef0.jpg)

**Comment by appocalyps** [comment]
hi, is there any solution foud for this issue, i'm having the same with GLPI 0.9 and data injection 2.8.0, please help

**Comment by stonebuzz** [comment]
Hi @appocalyps 

With glpi 9.5 and datainjection 2.8.0, plus is CSRF compliant

```php
$PLUGIN_HOOKS['csrf_compliant']['datainjection'] = true;
```
