### ISSUE TITLE
I do not see the option in mapping to model 

### ISSUE THREAD

**Issue by mays1509** [pluginsGLPI/datainjection#102]
It comes out blank and does not give me the option to select the tables and fields.

What could be affecting me?

![file injection model](https://user-images.githubusercontent.com/33699462/42380108-c9040b3a-80fa-11e8-9f8a-8ffaf40a7c68.png)

![file injection mapping](https://user-images.githubusercontent.com/33699462/42379991-69602e34-80fa-11e8-98b2-ab38751ab126.png)

GLPI 9.2.2

**Comment by trasher** [comment]
9.2.2 is no longer supported. Please try with GLPI 9.3 and corresponding plugin version.
Feel free to reopen if the bug persists.

**Comment by cedric-anne** [comment]
Hi,

For information a bug like this one has been fixed in 2.5.2 : https://github.com/pluginsGLPI/datainjection/releases/tag/2.5.2

Regards.

**Comment by mays1509** [comment]
With version 2.5.2 if it works for me, thanks
