### ISSUE TITLE
Field "Name"

### ISSUE THREAD

**Issue by BaptisteHsm** [pluginsGLPI/datainjection#107]
Bonjour,

J'ai un problème lors de mon injection, dans la table "ordinateur" je n'ai pas le champs "Nom". 
Il m'est donc impossible de faire l'import sachant que c'est mon champt de liaison. 

GLPI : 9.3
Datainjection : 2.6.1

---
Good morning,

I have a problem during my injection, in the computer table i have not the Name field. 
It's impossible for me to make the import knowing that it is my field of connection. 

GLPI : 9.3
Datainjection : 2.6.1

**Comment by cedric-anne** [comment]
Duplicates https://github.com/pluginsGLPI/datainjection/issues/103.
