### ISSUE TITLE
Call webservices for upload document

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/datainjection#11]
http://forum.glpi-project.org/viewtopic.php?id=154932

The method is not called with corrects parameters ($params, $protocol, $filepath)

**Comment by bastienprost** [comment]
Bonjour,

Merci pour votre réponse. Pouvez-vous me dire où je peux trouver une documentation afin de corriger ma commande? Je l'ai cherché mais sans succès...
D'avance merci,
Bastien
