### ISSUE TITLE
I can't update a computer's with a id column as keyed field.

### ISSUE THREAD

**Issue by vv0rk** [pluginsGLPI/datainjection#112]
When I create new model to update a computer's information, I can't select the id field to link a csv file with glpi data.
That is feature or bag?

**Comment by vv0rk** [comment]
Hi
Anybody ask to me?

**Comment by OscarBeiro** [comment]
Looks like a #103 dup

**Comment by cedric-anne** [comment]
Hi,

It is not possible to map ID field. The matching with existing data will be made using fields marked as "Link field" in the mapping configuration of your import.

Regards

**Comment by vv0rk** [comment]
Hi Anne, 
I need massive update existing assets with new data.
I see the workflow: 
1. to export existing a glpi's assets into a csv file
2. To send the file to colleagues for filling
 data
3. to update a glpi's assets with data from the collegues file with help a datainjection's plugin

for successfull realisation this workflow I need a mapping Id.

**Comment by cedric-anne** [comment]
Hi,

This feature does not exists and I donot know if it is easy to implement or not.

What I can suggest is that you use another field for your mapping, like "inventory number", "serial number", or "uuid".

Regards
