### ISSUE TITLE
Data injection csv file issue, header issues 

### ISSUE THREAD

**Issue by islt** [pluginsGLPI/datainjection#113]
Hello, I'm trying to import a csv file to create new computer assests, but am I having issues with the header of the file. The values are showing in one line, ie value,value,value rather than the listing expected to be able to link the fields. 

As shown here with a very simple csv: 
![csv-import](https://user-images.githubusercontent.com/42353863/44047570-a42cf02a-9f26-11e8-95b9-f6b302945468.JPG)

I'm using v9.3.0 (in a docker container) and File injection plugin 2.6.1

**Comment by OscarBeiro** [comment]
Looks like a #103 dup

**Comment by cedric-anne** [comment]
Hi,

It seems that plugin was initialy made to handle multiple file formats (csv, xml, ...), but only csv is implemented for now.
As format is not defined on creation form, specific fields (delimiter and presence of header for csv) are not available on creation and takes default DB values (`;'` for delimiter). If you want to update it, you have to go back to "Model" tab after clicking "Add" button.

The UI should be enhanced to display these fields on creation.

Regards

**Comment by islt** [comment]
Thanks Cedric-Anne, I changed my commas to semi-colons in my csv files and that's looking better.
