### ISSUE TITLE
Missing field in mapping 

### ISSUE THREAD

**Issue by dytrip77** [pluginsGLPI/datainjection#115]
datainjenction version : 2.6.1

Hi,
There is missing field while doing the mapping. If I continue with this, injected data will be incomplete as it missing crucial info such as serial number, hostname etc. Computer imported to GLPI 9.3 using OCS.

![datainject](https://user-images.githubusercontent.com/22068278/44129748-8346d216-a07c-11e8-84dc-0ed392587054.JPG)

**Comment by dytrip77** [comment]
Just saw this https://github.com/cedric-anne/glpi-plugin-datainjection/commit/351c78f86fa1ebcdf40c891e2351a1631948ae6b

Much better improvement but there are still missing field 

![inject2](https://user-images.githubusercontent.com/22068278/44130264-2b9f213c-a07f-11e8-9db2-81811383b773.JPG)

**Comment by cedric-anne** [comment]
Hi,

I did not check all fields, but you should be able to find most of them using another table, for example, "Operating system" fields are in "Operating system" table.

Regards

**Comment by cedric-anne** [comment]
By the way, did you import from OCS using a manual export or did you use the "OCS inventory ng" plugin (https://github.com/pluginsGLPI/ocsinventoryng) that has been made for this usage ?

**Comment by dytrip77** [comment]
Thanks for the clarification https://github.com/cedric-anne

Import was done using ocsinventoryng plugin.
