### ISSUE TITLE
Import association computer and human resource

### ISSUE THREAD

**Issue by vv0rk** [pluginsGLPI/datainjection#118]
I can't import association of the computer and the user of Human Resource.
What is it bug or feature?

**Comment by vv0rk** [comment]
I mean a massive association from csv file

**Comment by cedric-anne** [comment]
Hi,

I do not know how the "Resources" plugin works, but if something has to be made to enable this feature, it is on "Resources" plugin. You should ask your question on their repository: https://github.com/InfotelGLPI/resources .

Regards
