### ISSUE TITLE
Entity importation

### ISSUE THREAD

**Issue by mohierf** [pluginsGLPI/datainjection#125]
I am trying to import entities from another instance of Glpi into my fresh new installation.

On my former Glpi I exported to a CSV file: 
![image](https://user-images.githubusercontent.com/2932687/45988991-03f91a00-c07a-11e8-90d4-6470044bcf20.png)

Note that the entities complete name contain the "Root entity" name as "Entité racine"

On the new Glpi, the result is 
![image](https://user-images.githubusercontent.com/2932687/45988979-ecba2c80-c079-11e8-86a1-5061226c3c3c.png)

The Root entity "Entité racine" is imported as a child of the current root entity despite that it has the same name.

 Is there any solution to restore a correct entity hierarchy ? Did I miss something ?

**Comment by OlinuxX** [comment]
It's been a long time and you probably found the solution since, but maybe this will be of help as it it is related : #105 

You don't need to put any parent entity in your .csv file, the default behaviour is to import under the Root entity.

**Comment by cedric-anne** [comment]
Hi all,

#217 should fix this issue. Could you test it ?

Regards
