### ISSUE TITLE
Can't import dropdown values that contain apostrophe

### ISSUE THREAD

**Issue by loicbenoit** [pluginsGLPI/datainjection#126]
### Steps to reproduce (which actions have you made) :
1. Create a [new dropdown field](https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#add-a-simple-dropdown-field) in GenericObject
2. Include an apostrophe in one of the dropdown item. For example: "Pelure d'orange"
3. Define an injection model in DataInjection for a custom object that uses that dropdown.
4. Use the CSV importation template to import a few objects. Use the value from step 2 in the dropdown field.

### Expected result :
Dropdown values that contain apostrophes are recognized and the numerical external ID is correctly inserted into the field.

### Actual result :
The value is not recognised with error message (Missing value / Donnée introuvable).
It works when I delete the apostrophe and stops when I add it back.

### Additional info
1. Must test if this also happens with dropdowns provided by GLPI
2. The issue may also be caused by plugin GenericObject, but it only occurs when importing CSV data with plugin DataInjection.
3. Using mass action works as expected: I can use mass action to set a dropdown value that contains an apostrophe.

Therefore, DataInjection is a good place to start searching for the cause.

### GLPI setup (Setup > General menu, System tab) :
GLPI 9.3.0 (/glpi => /opt/bitnami/apps/glpi/htdocs) Installation mode: TARBALL

Operating system: Linux debian 4.9.0-6-amd64 no1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 PHP 7.1.18 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, 	mongodb, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, soap, sockets, sqlite3, 	standard, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="120" memory_limit="128M" post_max_size="40M" safe_mode="" session.save_handler="files" 	upload_max_filesize="40M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.22 	Server SQL Mode:  	Parameters: root@localhost/glpi3dev 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed APCu extension is not present CAS extension is not present Database version seems correct (5.7.22) - Perfect! /opt/bitnami/apps/glpi/htdocs/config : OK /opt/bitnami/apps/glpi/htdocs/files : OK /opt/bitnami/apps/glpi/htdocs/files/_dumps : OK /opt/bitnami/apps/glpi/htdocs/files/_sessions : OK /opt/bitnami/apps/glpi/htdocs/files/_cron : OK /opt/bitnami/apps/glpi/htdocs/files/_graphs : OK /opt/bitnami/apps/glpi/htdocs/files/_lock : OK /opt/bitnami/apps/glpi/htdocs/files/_plugins : OK /opt/bitnami/apps/glpi/htdocs/files/_tmp : OK /opt/bitnami/apps/glpi/htdocs/files/_cache : OK /opt/bitnami/apps/glpi/htdocs/files/_rss : OK /opt/bitnami/apps/glpi/htdocs/files/_uploads : OK /opt/bitnami/apps/glpi/htdocs/files/_pictures : OK /opt/bitnami/apps/glpi/htdocs/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/opt/bitnami/apps/glpi/htdocs/lib/htmlawed) SimplePie version 1.5.1 in (/opt/bitnami/apps/glpi/htdocs/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/opt/bitnami/apps/glpi/htdocs/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/opt/bitnami/apps/glpi/htdocs/vendor/michelf/php-markdown/Michelf) true/punycode in (/opt/bitnami/apps/glpi/htdocs/vendor/true/punycode/src) iacaml/autolink in (/opt/bitnami/apps/glpi/htdocs/vendor/iamcal/lib_autolink) sabre/vobject in (/opt/bitnami/apps/glpi/htdocs/vendor/sabre/vobject/lib)

Not active

Way of sending emails: PHP

Plugins
        fields               Name: Additionnal fields             Version: 1.8.2      State: Enabled
	barcode              Name: Barcode                        Version: 2.2.0      State: Enabled
	etl                  Name: ETL                            Version: 0.0.1      State: Enabled
	datainjection        Name: File injection                 Version: 2.6.3      State: Enabled
	order                Name: Gestion des commandes          Version: 2.2.0      State: Enabled
	genericobject        Name: Objects management             Version: 2.6.2      State: Enabled
	reports              Name: Rapports                       Version: 1.11.3     State: Enabled
[/code]

**Comment by ddurieux** [comment]
Can you test with this fix ? https://github.com/pluginsGLPI/datainjection/pull/128/files

**Comment by loicbenoit** [comment]
It did not solve the issue.

It also appears to escape values twice as "Pelure d\\\'orange" instead of "Pelure d\'orange".
