### ISSUE TITLE
Updating User information error

### ISSUE THREAD

**Issue by iancomline** [pluginsGLPI/datainjection#129]
GLPI Version: 9.3.1
Injection Version: 2.6.3

When trying to update the user information i get a error on each user that has different data in the database:
![screen shot 2018-09-29 at 23 20 01](https://user-images.githubusercontent.com/21229444/46250950-3d48d580-c43e-11e8-9686-3fa8edef48f9.png)
Does anyone know how to fix this error.
Also the import doesn't fill out the email address when importing have seen a few things to try but nothing seems to be working.
Thanks
Ian

**Comment by marcosenunes** [comment]
I´m having the same error...

**Comment by gaetanfl** [comment]
Hi,
I had the issue with emails too, but I found the issue looking at the source code. You need to allow your model to create dropdown 
![image](https://user-images.githubusercontent.com/36162164/51268056-670f1380-19bf-11e9-8b35-9e153a0d9eaa.png)
