### ISSUE TITLE
Simcard import - 9.3

### ISSUE THREAD

**Issue by mnitka** [pluginsGLPI/datainjection#130]
Hello,

Is this possible to import Sim cards? In GLPI 9.1 with Simcard plugin there was no problem but here I do not see any option to import sim cards as components.

Regards,

**Comment by nsi-test** [comment]
I have the same question.
Simcards since GLPI 9.3 are components (like memory for instance). Is it intentionally omitted?
(ver. 2.6.4 here)
Regards

**Comment by Wolvverine** [comment]
https://github.com/pluginsGLPI/datainjection/issues/249#issuecomment-1599404500
