### ISSUE TITLE
Possibility to deploy PDU and UPS

### ISSUE THREAD

**Issue by lolokai** [pluginsGLPI/datainjection#134]
Hello,
Can you add the possibility to inject PDU and UPS with this plugin ?
Best regards,

**Comment by stonebuzz** [comment]
Hi @

actually, fields is not compatible with PDU / UPS part, but it's possible to implement it and it'sinteresting

You can propose a PR to implement this feature, or
If you want to refactor this part quickly, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards
