### ISSUE TITLE
Import computer - components memory

### ISSUE THREAD

**Issue by vgelot** [pluginsGLPI/datainjection#137]
During computers import (with components memory), the size by default of the components is reset to 0 Mio.
Try to import "Memory - Name".
Try to import both "Memory - Name" and "Memory - Size by default".
Same result
GLPI v9.3.2
Datainjection v2.6.4
CSV format : comma and field without quote

**Comment by stonebuzz** [comment]
Hi @vgelot

your version is old, can you update glpi and datainjection to latest version ?
