### ISSUE TITLE
Import phones - field comment

### ISSUE THREAD

**Issue by vgelot** [pluginsGLPI/datainjection#138]
During phones import, the field comment is not updated, but append.
The carriage return is replace by 'n'
GLPI v9.3.2
Datainjection v2.6.4
CSV format : comma and field without quote

**Comment by stonebuzz** [comment]
Hi @vgelot 

your version is old, can you update glpi and datainjection to latest version ?

**Comment by misejoh** [comment]
Hello, 
Same situation here, I'm using datainjection on Devices, and the field gets appended every time I do an import on the same object.
About the version, mine is: datainjection 2.7.1 and GLPI 9.4.6

What else can I provide?
Thanks.
