### ISSUE TITLE
Import Line

### ISSUE THREAD

**Issue by nprevel** [pluginsGLPI/datainjection#139]
Hello,
I can't import line in my GPLI 9.3.2 and Datainjection 2.6.4.
There isn't the field in the list.

Regards,

**Comment by nprevel** [comment]
Hello,
I updated GLPI in 9.4.0 and Datainjection in 2.7.0 and i can't import line too.

Regards,

**Comment by mfrakka** [comment]
Hi, we are facing the same issue with GLPI in 9.4.0 and Datainjection in 2.7.0 

Putting interface in debug mode we get this errors:

`PHP Notice: Undefined property: PluginDatainjectionBackendcsv::$file in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 200
PHP Warning: fopen(): Filename cannot be empty in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 200
PHP Warning: fread() expects parameter 1 to be resource, bool given in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 205
PHP Warning: fseek() expects parameter 1 to be resource, bool given in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 207
PHP Warning: fgetcsv() expects parameter 1 to be resource, bool given in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 226
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 231
PHP Notice: Trying to access array offset on value of type null in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 232
PHP Warning: fgetcsv() expects parameter 1 to be resource, bool given in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 226
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 231
PHP Notice: Trying to access array offset on value of type null in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 232
PHP Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 217
PHP Notice: Undefined property: PluginDatainjectionBackendcsv::$file in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 245
PHP Warning: unlink(): No such file or directory in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php at line 245`


# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo) (<- Oracle Linux!)
# php74 -v
PHP 7.4.0RC4 (cli) (built: Oct 15 2019 11:28:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0RC4, Copyright (c), by Zend Technologies

allow_url_fopen -> On

**Comment by stonebuzz** [comment]
Hi @nprevel 

actually, datainjection is not compatible with simcard / line part, but it's interesting

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here GLPI Network

Best regards

**Comment by stonebuzz** [comment]
Duplicate with #162

**Comment by stonebuzz** [comment]
About your second problem  can you open anther issue ?

Best regards
