### ISSUE TITLE
Import doublon avec fusioninventory

### ISSUE THREAD

**Issue by cyrilLah** [pluginsGLPI/datainjection#142]
Bonjour

Je suis en train de mettre en place le plugin

Sauf que j'ai un souci lors de l import

J'ai deux sources pour le moment:

Un fichier csv venant d'une source externe et FusionInventory

Certains postes n'ont pas de lien réseau et donc impossible d utiliser fusion. d'autres parts tous les postes ne sont pas encore remontés via fusion

Bref je prends ma base de données en csv avec l integralité du parc. Tout fonctionne tres bien

Sauf que certains postes sont deja remontés par fusion et je souhaite que lors de l import si fusion l a remonté alors le plugin data ne le remonte pas . Par exemple si le numero de serie existe, alors pas d import

Merci de votre aide et de votre travail

**Comment by stonebuzz** [comment]
Hi @cyrilLah 

can you give use more informations ?

- glpi version
- datainjection version
- fusioninventory version

Best regards
