### ISSUE TITLE
Data Injection Error with password

### ISSUE THREAD

**Issue by Chabbinou** [pluginsGLPI/datainjection#144]
Hi everyone,

I just installed DataInjection 2.6.4 on my GLPI 9.3.1

I created a template for my import : 

- Actif;Identifiant;Mot de passe;Nom de Famille; Prénom;Téléphone

- 1;toto.tata:toto.tata1;DURANd;Michel;0102030405

But when I try to import my fyle, I got this : 

> Au moins un champ obligatoire n'est pas rempli (Mot de passe) | Import impossible | Indéterminé

Is there is a problem with the password ?

Thanks
Chabbinou

**Comment by stonebuzz** [comment]
Hi @Chabbinou 

can you retry with the latest version of glpi and datainjection.

Best regards
