### ISSUE TITLE
GLPI 9.3.3 issue not launching

### ISSUE THREAD

**Issue by MANGACORP** [pluginsGLPI/datainjection#145]
Hello,

Thanks for all your amazing works.
Please we have an issue to make work data injection.
Could you pleased help me ?

We well install it in /glpi/plugins
We check firewall/permission...
Please have a look to the screenshot.
[
![ssh-glpi](https://user-images.githubusercontent.com/47238727/52108622-3fe15480-2603-11e9-9c70-607f9dad434e.png)
](url)

Thank you so much for your help

Sincerely

Djezon

**Comment by stonebuzz** [comment]
Hi @MANGACORP 

first, can you try with latest version of GLPI and datainjection ?

check permission for datainjection folder and files.

Best regaards
