### ISSUE TITLE
MySQL 5.5 compatibility

### ISSUE THREAD

**Issue by benoiton** [pluginsGLPI/datainjection#146]
In table glpi_plugin_datainjection_models, field date_mod is defined as "datetime NOT NULL DEFAULT CURRENT_TIMESTAMP", which is supported only by MySQL 5.6.5+.

See "Automatic Timestamp Properties Before MySQL 5.6.5" section on [MySQL 5.6 manual](https://dev.mysql.com/doc/refman/5.6/en/timestamp-initialization.html).

[GLPI database requirement](https://glpi-project.org/DOC/EN/glpi/prerequisite_db.html) is only MySQL 5.5.

I see 3 options:

- Explicit requirement in doc
- Change datetime into timestamp
- Replace CURRENT_TIMESTAMP with trigger (not always supported in PaaS)

```
`date_mod` datetime NOT NULL DEFAULT '0000-00-00 00:00:01',
...
CREATE TRIGGER glpi_plugin_datainjection_models_trigger
BEFORE INSERT ON glpi_plugin_datainjection_models FOR EACH ROW
BEGIN           
    IF (NEW.date_mod = '0000-00-00 00:00:01') THEN
        SET NEW.date_mod = now();
    END IF;
END
```

**Comment by cedric-anne** [comment]
Hi,

See https://github.com/pluginsGLPI/datainjection/issues/95#issuecomment-433929106

Regards

**Comment by benoiton** [comment]
OK. Option 1. Sorry for the noise.

I'm stuck on a MySQL v5.5. Is there any major drawback to set date_mod as NULL ?

**Comment by cedric-anne** [comment]
I think you can use `datetime NOT NULL DEFAULT '0000-00-00 00:00:00'`. Someone says it was working on #95.

**Comment by benoiton** [comment]
Thanks
