### ISSUE TITLE
Lien contact/fournisseur avec la v2.6.4

### ISSUE THREAD

**Issue by felag** [pluginsGLPI/datainjection#147]
En important les fournisseurs et les contacts, je n'ai pas réussi à les lier entre eux.

J'ai essayé plusieurs modèles d'import:
- fournisseurs et contacts dans un même CSV: un contact avec le fournisseurs correspondant sur la même ligne: cela me créé un contact vide.
- un modèle pour les contacts et un autre pour les fournisseurs, avec le champ de lien contacts/fournisseurs dans le fichier des fournisseurs
- un modèle pour les contacts et un autre pour les fournisseurs, avec le champ de lien contacts/fournisseurs dans le fichier des contacts

Ci-joints les différents fichiers utilisés.

Comment faire pour lier des fournisseurs et des contacts ?

**Comment by felag** [comment]
Ah mince, j'ai oublié les fichiers: les voici.

Import 1: contacts et fournisseurs dans le même CSV: [fournisseurs_contacts.csv.txt](https://github.com/pluginsGLPI/datainjection/files/2901385/fournisseurs_contacts.csv.txt)  

Import 2: contacts et fournisseurs dans 2 CSV, avec le lien côté CSV fournisseurs:  [contacts.csv.txt](https://github.com/pluginsGLPI/datainjection/files/2901388/contacts.csv.txt) [fournisseurs.csv.txt](https://github.com/pluginsGLPI/datainjection/files/2901389/fournisseurs.csv.txt)  

Import 3: contacts et fournisseurs dans 2 CSV, avec le lien côté CSV contacts: [contacts.csv.txt](https://github.com/pluginsGLPI/datainjection/files/2901393/contacts.csv.txt) [fournisseurs.csv.txt](https://github.com/pluginsGLPI/datainjection/files/2901394/fournisseurs.csv.txt)

**Comment by stonebuzz** [comment]
Hi @felag 

try this

1 - import supplier without any informations about contact
2 - import contact

at mapping step do this :

![image](https://user-images.githubusercontent.com/7335054/73273260-fe6a9180-41e3-11ea-8fef-18dd174f80fc.png)

Column associated to "associated supplier" need to have supplier id.

Best regards

**Comment by felag** [comment]
Hi @stonebuzz,
I have tried it, supplier got imported, contact got imported but not link between them !

Please note that I have same behavior after upgrade: GLPi v9.4.5 and datainjection v2.7.1.
:cry:

**Comment by stonebuzz** [comment]
Hi  @felag 

can you check logfile ?

Best regards

**Comment by felag** [comment]
Hello @stonebuzz,
I have used simplified import files: 
[fournisseurs.csv.txt](https://github.com/pluginsGLPI/datainjection/files/4274844/fournisseurs.csv.txt) and [contacts.csv.txt](https://github.com/pluginsGLPI/datainjection/files/4274843/contacts.csv.txt).

Here is what happens:
- supplier get created without problem
- at contact import I have following error message in logs:
  > Data not found (Associated suppliers='12')

I see nothing in ``…/glpi/files/_log/``. Is there any logfile in particular to check ?
