### ISSUE TITLE
L'import de la valeur ne se fait pas correctement.

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/datainjection#15]
Hello,

La valeur quand elle est saisi dans les infos complementaires n'est pas importée.

Merci

**Comment by btry** [comment]
Il faut activer "Mise à jour des champs existants" pour que la valeur soit effectivement importée.

Il semble que les autres valeurs (numéro de commande en l'occurrence et à minima) ne soit pas impactée par le paramétage. Du coup, ca ressemble bien à un bug.

**Comment by btry** [comment]
TODO : Faire en sorte que le champ valeur soit mis à jour comme les autres champs quand "Mise à jour des champs existants" est à Non.
