### ISSUE TITLE
Wrong Content-Length calculation in Modelcsv::showSample

### ISSUE THREAD

**Issue by loicbenoit** [pluginsGLPI/datainjection#150]
In PluginDatainjectionModelcsv::showSample, the string length computation for the Content-Length header is wrong.

* Content-Length header expects a number of bytes, not a number of characters.
* mb_strlen returns a number of characters, not the byte count.
* Should be using strlen instead.

### Problem description
When a field label contains accentuated characters, the CSV sample gets truncated by the browser, because the byte count is wrong.

For example:
mb_strlen("abcd àêîôù"); //10 characters
strlen("abcd àêîôù"); //15 bytes

### Expected
When sending "abcd àêîôù", the browser should get all 15 bytes of "abcd àêîôù"

### Current result
When sending "abcd àêîôù", the browser cuts after 10 bytes.

### Solution
Use strlen instead of mb_strlen on the following line:
header('Content-Length: '.strlen($sample, 'UTF-8'));

**Comment by loicbenoit** [comment]
Original code:
header('Content-Length: '.**mb_strlen($sample, 'UTF-8')**);

Corrected code:
header('Content-Length: '.**strlen($sample)**);

**Comment by stonebuzz** [comment]
Hi @loicbenoit 

Thanks

PR need to be fixed.

See my comment.

Best regards
