### ISSUE TITLE
Certificates Import

### ISSUE THREAD

**Issue by HaZet1968** [pluginsGLPI/datainjection#151]
Is it possible to enhance the plugin to import certificates? That would be nice.

**Comment by stonebuzz** [comment]
Hi @HaZet1968 

actually, datainjection is not compatible with certificates part , but it's possible and  interesting

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards

**Comment by fabrepe** [comment]
Hi,

As GLPI v10 add certificates in core, injection of data seems to be simplified.
I'm not used to develop there but gave it a try. Please let me know if something's wrong with it.
