### ISSUE TITLE
data injection progress bar

### ISSUE THREAD

**Issue by ccastelb** [pluginsGLPI/datainjection#152]
recently updated to the version of glpi 9.4.1.1 with the plugin data injection in its version 2.7.0,
is installed in xammp
php 7.2.12
apache 2.4.37
other computers of test is xammp
7.3.3
happens that at the moment of carrying out the massive load, the browser screen does not show the progress of the load, it is simply blank, underneath it is performing the operation but the progress bar that was displayed in previous versions is not shown.
I began to make a new installation of glpi, replace the plugin on several occasions with a new download from the official plugins page, try to perform it on another computer, but even so the result remains the same, someone has some information about this behavior, or someone else is going through the same thing?
Any help would be appreciated

**Comment by zrcorsica** [comment]
similar problem here with latest version of glpi and data injection. I try to import large csv file that worked fine with old version of glpi (9.3) but it is very slow and web page becomes blank...

please fix it ! (centos 7.6, glpi 9.4.1)

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))
