### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by jeremylcgn** [pluginsGLPI/datainjection#153]
Hello,
When i import my csv, i have this problem (i'm in administrator mod)
![Capture](https://user-images.githubusercontent.com/17963177/56291705-0d38f980-6126-11e9-9032-ad176d82f94a.PNG)
I can't do an update of my existing PCs.
Thanks for your help !

**Comment by stonebuzz** [comment]
Hi @jeremylcgn 

can you give us more informations

- glpi version
- datainjection version
- screenshot about model configuration 

Best regards
