### ISSUE TITLE
Pas de signalement d'erreur

### ISSUE THREAD

**Issue by CNAF35** [pluginsGLPI/datainjection#156]
Lors de l'injection d'un fichier d'ordinateur nous souhaitons modifier le champ utilisateur.
Dans le fichier .csv la donnée contient un nom et un prénom.
Avec ce nom et ce prénom on trouve plusieurs personnes (homonymie).
Lors de l'injection du fichier, aucun signalement indiquant que cette donnée a posé problème, et pourtant le champ utilisateur n'est pas renseigné.
Dans le cas ou le nom et le prénom font référence à une unique fiche, alors le système fonctionne bien.

Serait-il possible de faire apparaitre un "warning" indiquant plusieurs choix d'utilisateurs possibles ?

Pour info notre version du plugin est la 2.4.2.

Cordialement,

**Comment by stonebuzz** [comment]
Hi @CNAF35 

which computer field have you linked to the column which have name and firstname ?

Best regards
