### ISSUE TITLE
Use of deleted librairy of GLPI core

### ISSUE THREAD

**Issue by yllen** [pluginsGLPI/datainjection#159]
![image](https://user-images.githubusercontent.com/12936722/62533911-16221800-b848-11e9-92f3-d87eaf31dd1b.png)

This error is for datainjection 2.4.2 but still present in master version

**Comment by stonebuzz** [comment]
Hi @yllen 

This issue hasn't evolved in a long time and is fixed by #160 

I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
