### ISSUE TITLE
MySQL 5.7 compatibility - Strict mode

### ISSUE THREAD

**Issue by ccapula** [pluginsGLPI/datainjection#16]
hi, i've got a problem with installation of this plugin in GLPI 0.90.5 MySQL version 5.7.15;
When i start the installation it says: 

Elaborazione in corso...
- Errore durante l'interrogazione del database: CREATE TABLE IF NOT EXISTS `glpi_plugin_datainjection_models` ( `id` int(11) NOT NULL auto_increment, `name` varchar(255) NOT NULL, `comment` text NULL, `date_mod` datetime NOT NULL default '0000-00-00 00:00:00', `filetype` varchar(255) NOT NULL default 'csv', `itemtype` varchar(255) NOT NULL default '', `entities_id` int(11) NOT NULL default '0', `behavior_add` tinyint(1) NOT NULL default '1', `behavior_update` tinyint(1) NOT NULL default '0', `can_add_dropdown` tinyint(1) NOT NULL default '0', `can_overwrite_if_not_empty` int(1) NOT NULL default '1', `is_private` tinyint(1) NOT NULL default '1', `is_recursive` tinyint(1) NOT NULL default '0', `perform_network_connection` tinyint(1) NOT NULL default '0', `users_id` int(11) NOT NULL, `date_format` varchar(11) NOT NULL default 'yyyy-mm-dd', `float_format` tinyint( 1 ) NOT NULL DEFAULT '0', `port_unicity` tinyint( 1 ) NOT NULL DEFAULT '0', `step` int( 11 ) NOT NULL DEFAULT '0', PRIMARY KEY (`id`) ) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_unicode_ci - L'errore è Invalid default value for 'date_mod'

WHy?

Thank you.

**Comment by alexramos2016** [comment]
Could you tell me please  if you can install the Data Injection.?

I have the same issue with the implementation.

**Comment by ccapula** [comment]
Hi,  I've solved following this guide

https://support.kayako.com/article/472-how-do-i-disable-mysql-strict-mode-on-the-server

Il 28 set 2016 4:28 PM, "alexramos2016" <notifications@github.com> ha
scritto:

**Comment by trasher** [comment]
Please note that GLPi itself is *not* MySQL 5.7 with strict mode compliant. See glpi-project/glpi#627

**Comment by cedric-anne** [comment]
Should be fixed by https://github.com/pluginsGLPI/datainjection/pull/84/commits/99d719ff73aaa83ced287388d3b5c2794ce0b5dd + https://github.com/pluginsGLPI/datainjection/pull/89/commits/8e6756f9973b87c4551deed085c4943e3347d6e2.
