### ISSUE TITLE
Haven't option to import racks

### ISSUE THREAD

**Issue by mecmav** [pluginsGLPI/datainjection#161]
Hello to all
I have a assets list from an external database (MS Access) and I'm trying to import some racks items, but I already try to add a model management in "Type of data to import", but haven't the option to import racks. 
Is there an issue or really don't have that option to import?

**Comment by DanielWhite95** [comment]
I have the same problem. Would be fantastic to import also racks from csv files

**Comment by stonebuzz** [comment]
Hi @mecmav 

actually, fields is not compatible with rack part, but it's interesting

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards
