### ISSUE TITLE
Import of "Lines" & "Simcards" requested

### ISSUE THREAD

**Issue by janpieters74** [pluginsGLPI/datainjection#162]
Hi
We just migrated to GLPI 9.4.3 from an older release where we used the Simcard-plugin. Nu we have to reorganise our Simcard management in GLPI, and i would like to use the datainjection to import all data from our simcards. I'm missing some data-sets (lines, simcard and the relation between both)

**Comment by stonebuzz** [comment]
Hi @janpieters74 

actually, datainjection is not compatible with simcard / line part, but it's interesting

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards

**Comment by sector7gp** [comment]
+1 
I want to leave SIM Card Management plugin

**Comment by Riesuu** [comment]
+1 I need to import 3000 sim

**Comment by EstevanCastro1** [comment]
I need to upload 50456 sim :(

**Comment by laurixia** [comment]
Mee too, I need import several Simcard

**Comment by meijin4** [comment]
+1
Same thing here, would love this feature!

**Comment by Wolvverine** [comment]
Is there a chance that there will be a sim card import option available soon?

#108
#130
#249
#284

**Comment by Wolvverine** [comment]
https://github.com/pluginsGLPI/datainjection/issues/249#issuecomment-1599404500

**Comment by petertuharsky** [comment]
Is there a possibility to implement SIM card import with GLPI 10?
