### ISSUE TITLE
import problem - I got ethernet mac addresses instead wifi mac addresses

### ISSUE THREAD

**Issue by abeulink** [pluginsGLPI/datainjection#163]
Hello developers, 

Please fix this problem, import to wifi mac address is impossible! 
I used existing fields from GLPI - network tab.
I waited for a fix for one year and I am still waiting :(
Please come on, guys!!!

Data Injection version 2.70
GLPI version 9.4.3

**Comment by stonebuzz** [comment]
Hi @abeulink 

Which itemtype are you try to import .

Can you gives us screenshots about your configuration 

You can propose a PR to implement / fix this part, 

If you want to speed up the process you can participate financially in its improvement.

Best regards
