### ISSUE TITLE
The plugin datainjection (file injection) has been activated but it is showing deactivated

### ISSUE THREAD

**Issue by sekp** [pluginsGLPI/datainjection#164]
Dear All,

I have installed GLPI 9.4.3 and data injection plugin is 2.7.0. After activated the plugin it is not activating just showing like deactivated.

**php status.php 
Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 659**
  *** PHP Warning(2): mkdir(): File exists
  Backtrace :
  :                                                  
  plugins/datainjection/setup.php:60                 mkdir()
  inc/plugin.class.php:168                           plugin_init_datainjection()
  inc/includes.php:104                               Plugin::load()
  status.php:34                                      include()

Thanks,
Sekar.P

**Comment by sekp** [comment]
It is fixed

**Comment by diego-mixfarma** [comment]
how did you fix it? Can you describe step by step how you solved this problem?
