### ISSUE TITLE
Field with mask

### ISSUE THREAD

**Issue by msizec** [pluginsGLPI/datainjection#167]
is it possible to import objects and generate a name and inventory name with a mask like 
<M####> or
<I\y-####\g>

It seems datainjection doesn't support this in template definition... but it is so useful 

thx

**Comment by stonebuzz** [comment]
Hi @msizec 

you need to use datainjection with geninventorynumber plugin -> https://github.com/pluginsGLPI/geninventorynumber

I am closing this issue, feel free to continue the discussion here if you want.

Best regards
