### ISSUE TITLE
[DATAINJECTION] Problème d'import (mise à jour)

### ISSUE THREAD

**Issue by enumanc** [pluginsGLPI/datainjection#168]
Bonjour,
Je tests le plugin DataInjection 2.7.0 sur une version 9.4.3 de GLPI et je rencontre le comportement suivant.
En important le fichier CSV suivant:
Nom;Numéro de série;Fabricant;Modèle;Commentaires
ETIC-2;2222222222;Zebra Technologies;ZD410;test commentaire 2
ETIC-3;3333333333;Zebra Technologies;ZD410;test commentaire 3b

L'import fonctionne bien mais lorsque je souhaite le réinjecter une seconde fois j'ai l'erreur suivante:
'Au moins une donnée n'a pas le bon format / type (date_creation='2019-09-20 11:43:29') Import impossible Mettre à jour 4'

La mise à jour ne fonctionne pas à cause du champ date mais le soucis c'est que je n'ai pas de colonne Date dans mon fichier CSV.

Une idée?

**Comment by stonebuzz** [comment]
Hi @enumanc 

which itemtype are you try to import ?

I can't reproduce with GLPI 9.4.5 and datainjection 2.7.0

can you test with latest version of each ?

Best regards
