### ISSUE TITLE
Add unmanagement import

### ISSUE THREAD

**Issue by jpnr79** [pluginsGLPI/datainjection#171]
To work with fusioninventory plugin, create the unmanagemet import, this is very nce because we can import many thing to the unmanagement. 

The unmanagement components can be export to many types of things and pass by rules of fusioninventory. and we can add more information to create or update 

![image](https://user-images.githubusercontent.com/26366055/68942049-67269e00-079f-11ea-8cf2-ade5c97ccb45.png)

**Comment by stonebuzz** [comment]
Hi @jpnr79 

actually, datainjection is not compatible with unmanaged part part, but it's interesting

You can propose a PR to implement this feature, or
If you want to refactor this part, please contact us here [GLPI Network](https://portal.glpi-network.com/plugins/formcreator/front/formdisplay.php?id=16)

Best regards
