### ISSUE TITLE
Entity import

### ISSUE THREAD

**Issue by protheusfr** [pluginsGLPI/datainjection#172]
Hello, 

I try to import entities in GLPI via datainjection.
My GLPI version is : GLPI 9.4.4 
My datainjection plugin version is: 2.7.0

My CSV file is quite simple :

```
Nom;Adresse;CP;Ville
TEST1;7 RUE DE TEST;75000;PARIS
```

After creating import model with the following setup : 
![Capture d’écran 2019-11-22 à 16 30 10](https://user-images.githubusercontent.com/1698825/69438579-93b15b80-0d45-11ea-8ac2-75d8a1fe7687.png)

I try to import a small file from root entity, but whatever I try, I obtain only the following result : 
![Capture d’écran 2019-11-22 à 16 33 02](https://user-images.githubusercontent.com/1698825/69438702-cbb89e80-0d45-11ea-9238-2cf710986d58.png)

![Capture d’écran 2019-11-22 à 16 33 08](https://user-images.githubusercontent.com/1698825/69438711-d1ae7f80-0d45-11ea-852a-83c796c6a8db.png)

I've I missed something ?

**Comment by Oswaldo-971** [comment]
Hello,
I got the same issue, did you find a solution ?

**Comment by stonebuzz** [comment]
Hi @protheusfr 


can you try this PR -> https://github.com/glpi-project/glpi/pull/6857

is for GLPI not datainjection

Best regards
