### ISSUE TITLE
Model creation button disabled, Data Injection 2.7.0

### ISSUE THREAD

**Issue by Antiheroe76** [pluginsGLPI/datainjection#173]
I just installed the Data Injection 2.7.0 plugin on Glpi 9.4.4.
My installation is Ubuntu 18.04 64bits Server, mysql See 14.14 Distrib 5.7.28 and PHP7.2

I get the following error:

Use an existing model
No model currently available. You can start the model creation by pressing the button: Model Management

I have disabled the model creation button.

I have reviewed the permissions for the profile and everything is enabled.

How can I solve that?

Regards

**Comment by b45h3r** [comment]
Hi,

I do have the same issue with GLPI 9.4.4. and Data Injection 2.7.0. I'm not even able to find the button Model Management. I have checked/unchecked the create setting for model management in profile section. But It keep telling "No model currently available. You can start the model creation by hitting the button: Model management". Any help would be appreciate. Thank you.

Best regards

**Comment by jlms77** [comment]
Exact me issue over here using GLPI 9.4.4. and Data Injection 2.7.0.

**Comment by femachado** [comment]
Same issue here over Glpi 9.4.5 and Data Injection 2.7.0.

Any updates? Thanks

**Comment by stonebuzz** [comment]
Hi 

can you see this

![image](https://user-images.githubusercontent.com/7335054/73254635-111e9f80-41bf-11ea-97a4-be384794c315.png)

check profil rights

![image](https://user-images.githubusercontent.com/7335054/73254672-25629c80-41bf-11ea-942d-e3f6e5156c61.png)

try to log out / log in after updated rights

Best regards

**Comment by femachado** [comment]
Thanks stonebuzz!

Yes, I'm a super-admin with exact the same permissions you sent. Yet, model management is still disabled.

![image](https://user-images.githubusercontent.com/2153697/73608541-3aff0a00-45a3-11ea-8c79-b45cb757053c.png)

:(

Thanks!
Fer

**Comment by femachado** [comment]
Thanks stonebuzz!

Yes, I'm a super-admin with exact the same permissions you sent. Yet, model management is still disabled.

![image](https://user-images.githubusercontent.com/2153697/73608541-3aff0a00-45a3-11ea-8c79-b45cb757053c.png)

:(

Thanks!
Fer

**Comment by femachado** [comment]
Update: i have also tried to login with a regular user (technician) applying first all file injection permissions to the profile. Logged out/in but the same issue.

![image](https://user-images.githubusercontent.com/2153697/73609174-d0050180-45a9-11ea-9435-e8972582f445.png)

**Comment by femachado** [comment]
Thanks stonebuzz.

I could solve it just hitting:

![image](https://user-images.githubusercontent.com/2153697/73609246-9385d580-45aa-11ea-8fca-8c7a5c4dc3bf.png)

After that, it shows me the model management page with the "+" option.

![image](https://user-images.githubusercontent.com/2153697/73609264-c039ed00-45aa-11ea-9dfe-75cfc868cf8a.png)

It's a little bit odd, but it's how it works!
