### ISSUE TITLE
Problem while importing in computer table : field "Name" receives no data

### ISSUE THREAD

**Issue by castorsenior** [pluginsGLPI/datainjection#174]
Hi,
All the fields are filled correctly, but the field "Name" stays empty. This problem seems to occur only for computers : everything works well for printers.
My environment : 
- GLPI 9.4.4
- DataInjection 2.7.0
- PHP 7.3
- HTTPD 2.4.6
- CentOS 7.7.1908
- CSV : the separator is ; and each field is surrounded with "
Thank you for your attention and your help !

**Comment by castorsenior** [comment]
Hi
When I activate php errors, nothing is written in the logs

**Comment by castorsenior** [comment]
Hi 
When I activate debug mode clicking on the bee (in glpi web interface on the right top of the screen), nothing is written in /var/www/glpi/files/_log.

**Comment by castorsenior** [comment]
The plugins itself tells everything is ok, but the data are not imported in the field "Name" :-(

**Comment by JeanMichelDrouet** [comment]
Hi, just see the same problem but in fact there are 2 field name and the second one works for me

**Comment by stonebuzz** [comment]
Hi @castorsenior 

can you disbled all plugins except datainjection, and retry ?

Best regards

**Comment by castorsenior** [comment]
Hi @stonebuzz 
Thank your very much for your attention ! 
I just did it, but the injection doesn't work : it freezes in the beginning.
![image](https://user-images.githubusercontent.com/12443836/73261318-20581a00-41cc-11ea-9a2a-d5f0fa6e58f4.png)

**Comment by stonebuzz** [comment]
Hi @castorsenior 

I confirm the bug, it's a translation problem, one of them ("name") is for the antivirus name

![image](https://user-images.githubusercontent.com/7335054/73267726-e8f06a00-41d9-11ea-805c-d2ac45fb386c.png)

Can you test this PR -> https://github.com/pluginsGLPI/datainjection/pull/178

Best regards

**Comment by castorsenior** [comment]
Hi @stonebuzz 

I tested your fix. Everything works perfect. Thank you very much :-)
After having putted the fix, I saw in my injection template :
![image](https://user-images.githubusercontent.com/12443836/74458323-d3419c80-4e89-11ea-8fa3-e5c3d96af4c2.png)
I could then select the good choice without having two times "Name" :  
![image](https://user-images.githubusercontent.com/12443836/74458399-efddd480-4e89-11ea-8370-070d29304d1f.png)
Thanks a lot !
With best regards,
Mikhael

**Comment by stonebuzz** [comment]
:+1: 

=)
