### ISSUE TITLE
Import Computer Pour mise à jour OS

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/datainjection#175]
Hello,

GLPI : 9.4.3
Plugin : 2.7.0

je souhaite realiser une mise à joru de masse de l'os d'ordinateur via un fichier CSV (en attendant la mise en place API)

j'ai defini un fichier CSV en entrée comportant Nom Ordinateur, OS et Version OS.

Voici la definition du modele d'import : 
![image](https://user-images.githubusercontent.com/42341169/72056078-3315b800-32cc-11ea-888b-7264d9f6ee15.png)

ainsi que la correspondance des champs
![image](https://user-images.githubusercontent.com/42341169/72056157-5a6c8500-32cc-11ea-97c4-6436eab9b11d.png)

lors de l'execution de l'import, l'ordinateur se retrouve avec 2 OS et non 1.
Je m'attendrais à une mise à jour de l'os, et non son ajout ?
Qu'aurai je mal paramétré ?

Merci de votre retour

**Comment by stonebuzz** [comment]
Bonjour @EC2311 

votre paramétrage est correcte, mais le plugin n'est pas en mesure de mettre à jour l'OS.

Il faudrait implémenter la notion de clé de réconciliation permettant au plugin de savoir s'il doit faire une création ou une mise à jour (car un PC peut avoir plusieurs OS).


Vous pouvez exprimer votre besoin ici -> https://glpi.userecho.com/

Ou participer financièrement à son développement en nous contactant ici  -> https://portal.glpi-network.com/contactez-nous

Je ferme ce ticket, n'hésitez pas à poursuivre la discussion ici si vous avez besoin

Bien cordialement

**Comment by EC2311** [comment]
Bonjour

Ok, merci pour la reponse

De ce fait j'ai commencé à ecrire un petit script, que j'ai integré directement dans le repertoire 'front' de datainjection.

j'ai incorporé 
![image](https://user-images.githubusercontent.com/42341169/72242930-d1668e00-35ea-11ea-9fcb-ea73b0529962.png)

ainsi qu'une boucle afin de lire les lignes de ce fichier
![image](https://user-images.githubusercontent.com/42341169/72242975-ea6f3f00-35ea-11ea-8aa7-47d57f28c4ed.png)

je pense qu'il doit me manquer le nécessaire afin de pouvoir lire (et voire ensuite mettre à jour) les tables nécessaires : mais je ne sais pas comment faire :( 

pourriez vous me donner quelques 'astuces' ou 'ficelles' ?

Le cas écheant je mettrai le contenu du script ici (ou un autre endroit) au cas où d'autres personnes seraient interessées par ce type de mise à jour.

Merci
