### ISSUE TITLE
Insertion Datas groupe avec Pere (Hierarchie)

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/datainjection#177]
Bonjour

But : integrer mettre à jour des noms de groupes d'un logiciel. Ces groupes sont définis dans une hierarchie (donc avec pere)

j'ai un ficheir Excel CSV contenant : Père, Nom, Description.
![image](https://user-images.githubusercontent.com/42341169/72887044-35840300-3d0b-11ea-95a2-42bcfb9684c2.png)

Lors de l'insertion, il n'arrive pas à creer ou mettre à jour les groupes 
![image](https://user-images.githubusercontent.com/42341169/72887115-5c423980-3d0b-11ea-9eb8-b56016e37087.png)

Si je supprime la colonne 'pere' la mise à jour/creation est ok, mais à la racine... alors que je vux la realiser sous le 'pere'...

PS : le groupe pere est bien present et existe bien dans le "groupe", à la racine... quoique je pense qu'il devrait être créé... au pire...

**Comment by stonebuzz** [comment]
Hi @EC2311 

can you try this :

for each group, define name (glpi completename) column like this  : 

- Père > Child 1
- Père > Child 2

remove "Père" column, and define completename as link fied

Best regards

**Comment by EC2311** [comment]
Hello
You mean doing this update in excel file with a column (pere+Child) in fact... ?

Best regards

**Comment by stonebuzz** [comment]
yes( like this: "pere > child") , and match this column with completename field

best regards

**Comment by EC2311** [comment]
Hello

Like this, it's ok : the parent group is also created. -> ok

But ;)
an other question : 
I try to add this kind of group linked at an user

At this level I have to use Datainjection -> user : ok
I rebuild the column completename.
![image](https://user-images.githubusercontent.com/42341169/74633737-9a901480-5162-11ea-928b-42c534f0cca5.png)

When executing the script : error : 
![image](https://user-images.githubusercontent.com/42341169/74633806-ca3f1c80-5162-11ea-8a1d-17ecf7b9451e.png)

How managing the 'import/update' of users belonging to group (with parent topic) ?
Thanks

**Comment by stonebuzz** [comment]
Can you retry without group as a link field ? (just keep user number)

If failed, retry with group name only (instead of completename)

Best regards

**Comment by EC2311** [comment]
I tried the 2 solutions

![image](https://user-images.githubusercontent.com/42341169/74645167-b2be5e80-5177-11ea-8c74-95118022929c.png)

I don't understand why it says 'user already exists.

By the way, with reflexion... 
In fact I think datainjection will net be able to manage the process.
I will have to create a batch 

The file I received contains the group whose users belong to (for a special product) and if user is not the file, then the group must be removed from user in GLPI...

Is it hard to do such a script ?

Thanks
Best regards

**Comment by stonebuzz** [comment]
Have you datainjection model to update object ?

**Comment by EC2311** [comment]
what do you mean ? I don't understand your remark. Which object ?

**Comment by stonebuzz** [comment]
![image](https://user-images.githubusercontent.com/7335054/74724016-e06cdb80-523b-11ea-8c8e-4ec465cdf271.png)

**Comment by EC2311** [comment]
here is the link I make
![image](https://user-images.githubusercontent.com/42341169/74733682-1c5c6c80-524d-11ea-996e-7bf142845316.png)

and 
![image](https://user-images.githubusercontent.com/42341169/74733717-326a2d00-524d-11ea-9958-73695bbb330b.png)

As I said previously, I would like that the group in csv file be added to the user (an other group is already present for user)

perhaps it's not possible with teh plugin?

NB : I am in 2.7.0 version

**Comment by EC2311** [comment]
I found

it's because of CSV file and data type with which I do the link.
The column must be characters and it appears as numeric.

In GLPI database this field is on 7 digits (left padded with 0) and csv consider it as numeric without 0 :(
so no link

**Comment by EC2311** [comment]
I wanted to do it for a greater file and after running I can't login into GLPI
Here is the error
 *** PHP Notice(8): Undefined index: NULL
  Backtrace :
  inc\plugin.class.php:218                           
  inc\plugin.class.php:315                           Plugin::loadLang()
  inc\plugin.class.php:318                           Plugin->{closure}()
  inc\plugin.class.php:287                           Plugin->checkPluginState()
  inc\plugin.class.php:123                           Plugin->checkStates()
  inc\includes.php:99                                Plugin->init()
  index.php:57                                       include()
{"user":"29782@xxxxxxxxxxxxxx","mem_usage":"0.000\", 1.97Mio)"}
