### ISSUE TITLE
Ecrasement date lors de l'injection de données financiéres

### ISSUE THREAD

**Issue by jlb5980** [pluginsGLPI/datainjection#18]
Bonjour

Nous rencontrons un problème d'injection au niveau des données financières.

Lors de l'injection de données type date,  les données non comprises concernant une date dans le fichier d'injection sont écrasées .

Exemple j'injecte un fichier avec le numéro de série en clé et simplement une mise à jour de la date de dernier inventaire physique > aprés injection par le plugin datainjection, les données : Date de livraison, Date de mise en service, Date de commande, date de commande,  Date de début de garantie sont écrasées.

En cherchant un peu, dans le fichier infocominjection.class.php  dans le répertoire du plugin datainjection :
Au niveau :

function reformat(&$values = array()) {
      foreach (array('order_date', 'buy_date', 'warranty_date', 'delivery_date',
                     'inventory_date') as $date) {
         if (!isset($values['Infocom'][$date])
            || $values['Infocom'][$date] == PluginDatainjectionCommonInjectionLib::EMPTY_VALUE) {
            $values['Infocom'][$date] = "NULL";

la dernière ligne me pose question :   $values['Infocom'][$date] = "NULL";
Si je commente cette ligne les données ne sont plus écrasées .

Les dernières versions du plugin semblent toujours avoir cette ligne et le problème semble persister 

Pour info je ne suis pas un développeur
Ma  question est donc peut on laisser en commentaire cette ligne ?

Cordialement

**Comment by trasher** [comment]
Ce problème a été corrigé, dans la version 2.4.2 du plugin. Pour le correctif, voir 8e022fe278ac1ac8b0caef6820dac95aa7a4ce86
