### ISSUE TITLE
Unable to show report in PDF format (fatal error)

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/datainjection#180]
Hi, 
I made a injection, it's work well, BUT, the PDF report at the end of import job says :
PHP Warning: require(../../../lib/ezpdf/class.ezpdf.php): failed to open stream: No such file or directory in /var/www/html/glpi/plugins/datainjection/front/export.pdf.php at line 32

Fatal error: require(): Failed opening required '../../../lib/ezpdf/class.ezpdf.php' (include_path='.:/usr/share/php') in /var/www/html/glpi/plugins/datainjection/front/export.pdf.php on line 32

First line is in red.

The text report is ok and the status at the end is "import was successfull" and is really successfull.

NOTE : The import is made on a genericobject plugin object, 

GLPI 9.4.5+datainjection 2.7.0

**Comment by cedric-anne** [comment]
Duplicates #159 .
Fixed in latest 2.7.1 release.

**Comment by mab18** [comment]
Hi, 
Excellent ! 2.7.1 juste today :-)
Many thanks

**Comment by mab18** [comment]
Hi,
Excellent ! 2.7.1 just today :-)
Many thanks
