### ISSUE TITLE
Data Injection PHP error

### ISSUE THREAD

**Issue by RLouisy826** [pluginsGLPI/datainjection#184]
Hello,
I have my GLPI server and these are my specs
- Windows Server 2012
- 4 Gb RAM
- Windows IIS 8
- PHP 7.4.2
- MySQL 5.6
- GLPI 9.4.5
<img width="568" alt="PHP_data_injection_error" src="https://user-images.githubusercontent.com/36987755/74339045-94391b80-4da3-11ea-9648-18d841b2c7a1.PNG">

During my installation i was instructed to move the "inetpub" folder to the D: drive (folder which by default goes on the C: drive),
This folder contains the "wwwroot" folder in which you have to put the glpi folder.
Since the folder changed location, i used PHP Manager to Redirect the "php.exe" and "php-cgi.exe" so glpi knows it's location.

My problem is when i try to inject data using the plugin i receive php errors that seem to be saying that it's unable to call functions.

Looking at the errors they seem to be coming from this file
D:\inetpub\wwwroot\glpi\plugins\datainjection\inc\backendcsv.class.php
On lines = 200, 205, 207, 217, 226, 231, 232, 245

Unfortunately upon inspecting said lines i don't seem to find anything abnormal is the error coming from another file ?

Thank you in advance.

**Comment by stonebuzz** [comment]
Hi @RLouisy826 

can you check the rights of the GLPI folder (and subfolder) for your web server

Best regards

**Comment by RLouisy826** [comment]
Hey @stonebuzz
Thanks for the advice, i tried what you said but sadly still nothing i keep getting the same PHP error even after changing the folder's rights
<img width="244" alt="Capture d’écran (4)" src="https://user-images.githubusercontent.com/36987755/74417293-c0f23f00-4e46-11ea-9d98-a1a21c36937a.png">
<img width="246" alt="Capture d’écran (3)" src="https://user-images.githubusercontent.com/36987755/74417296-c18ad580-4e46-11ea-807f-f9832d1b67a8.png">

**Comment by mab18** [comment]
Hi,
Could you show to us the rights on (...)/glpi/files/_plugins/datainjection/ ?

**Comment by stonebuzz** [comment]
Hi @mab18 

can you test this PR 

https://github.com/pluginsGLPI/datainjection/pull/189

Best regards

**Comment by mab18** [comment]
@stonebuzz I have to env to test with PHP 7.4 :-(

**Comment by stonebuzz** [comment]
Your spec mentionned PHP 7.4.2 ?

**Comment by mab18** [comment]
@stonebuzz @RLouisy826 is the initiator of this bug ;-)

**Comment by stonebuzz** [comment]
Sorry =)

you can still test with your version of php

Best regards

**Comment by mab18** [comment]
I don't know how to test correctly : I don't have problems for now.
Could you help me to get the problem for testing ? Just note than I can't install PHP 7.4 :-(
I have 7.2 and 7.3 PHP for testing.

**Comment by stonebuzz** [comment]
Just install plugin, enable GLP debug mode
 try an injection and see warning 

![image](https://user-images.githubusercontent.com/7335054/75426126-4811dd80-5944-11ea-9586-17623a3fa726.png)

After, test this PR #189 
and warning disappear

Best regards

**Comment by mab18** [comment]
Hi,
I try your description.

**Comment by mab18** [comment]
Note: I already made a ticket on https://forge.glpi-project.org/issues/5600 without answer for the moment.

**Comment by stonebuzz** [comment]
Yes it's a problem on appliance plugin :disappointed:

**Comment by mab18** [comment]
I didn't insert the patch and I didn't have any (other) error.
How @RLouisy826 have this problem ? Is this only with PHP 7.4 ?

**Comment by stonebuzz** [comment]
I haven't tested on all versions of PHP.

this is a PHP "extends" implementation error with variable declaration.
which now raises a warning

best regards

**Comment by mab18** [comment]
Ok for that, I just finished to test on my PHP 7.3.11. Same thing : no error as @RLouisy826 

I'm going to add the fixes you offer, without being able to test them.

**Comment by mab18** [comment]
Oh...
Now an error : 
`Fatal error: Access level to PluginDatainjectionBackendcsv::$delimiter must be protected (as in class PluginDatainjectionBackend) or weaker in /var/www/html/glpi/plugins/datainjection/inc/backendcsv.class.php on line 30`
and nothing to validate nor other thing. GLPI menu is here, but no buttons in the page.

**Comment by stonebuzz** [comment]
I updated the PR this morning for this problem, can you test it with the latest changes ?

Best regards

**Comment by mab18** [comment]
Have you got the link please ?

**Comment by stonebuzz** [comment]
Link to PR https://github.com/pluginsGLPI/datainjection/pull/189 
Link to commit https://github.com/pluginsGLPI/datainjection/pull/189/commits/5f55c05e904481492f677b6f5ff8e7e184cb1f31
Link to patch https://github.com/pluginsGLPI/datainjection/pull/189/commits/5f55c05e904481492f677b6f5ff8e7e184cb1f31.patch 

=)

**Comment by mab18** [comment]
I try again...

**Comment by stonebuzz** [comment]
great :+1:

**Comment by mab18** [comment]
I try on PHP 7.3.11 now, I don't have more.

**Comment by mab18** [comment]
I try on PHP 7.3.11 now, I don't have more.

**Comment by RLouisy826** [comment]
Hello @stonebuzz @mab18 ,
Firstly i'd like to thank you both for taking your time to address my issue,
Unfortunately i was unable to respond lately because i returned to school for a good while.

@mab18 are you using Windows Server 2012 (not 2012 R2)
Perhaps this is why you could not reproduce the problem ?

**Comment by RLouisy826** [comment]
The only significant difference between these 2 version is the presence of the service pack (i don't know which one exactly)
Perhaps my version of the OS is missing something ?

**Comment by mab18** [comment]
@RLouisy826 : 
I use Ubuntu 18.04.4 on my environment.

**Comment by RLouisy826** [comment]
Hello, 
I have an update, 
It was indeed Windows Server 2012 that was creating the issue.
I do not know exactly what the problem is but i can confirm that it has something to do with the OS.
But thank you once again for looking into my issue.

Best Regards,
