### ISSUE TITLE
wrong translation FR - validation of file

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/datainjection#186]
Hi,
When a take a new structure of file, I see some translation problems : 
![image](https://user-images.githubusercontent.com/55535560/74925737-0b3e6780-53d5-11ea-8ac3-9a57dfb81e16.png)
Should be : "Attention : les colonnes existantes vont êtres écrasées", was correct in 2.7.0
After that, we see : 
an mixing frenglish at lower right : 
![image](https://user-images.githubusercontent.com/55535560/74925236-22c92080-53d4-11ea-8f8b-b0128819d3b2.png)
We should see "Le fichier est ok." and not "The fichier est ok."

context : GLPI 9.4.5+DI 2.7.1

**Comment by trasher** [comment]
Hi,
Translations are done on transifex: https://www.transifex.com/teclib/glpi-plugin-datainjection/dashboard/

**Comment by mab18** [comment]
Thanks,
I done the translations in transifex.

**Comment by mab18** [comment]
Hi,
Please, could you help me to compile de .mo (I read [this](https://glpi-plugins.readthedocs.io/fr/latest/empty/#compile-mo) ) but I don't have `./vendor/bin/plugin-release` in the directory :-/

**Comment by stonebuzz** [comment]
Hi @mab18 what do you want to do ?

**Comment by mab18** [comment]
I'm sorry to don't know what to do to compile the .PO to .MO...
So, I have to text file translated, but it doesn't works alone.

**Comment by stonebuzz** [comment]
You need to use msgfmt

https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/msgfmt.html

to compile po to mo.

Like this ```msgfmt xxx.po -o xxx.mo```

after you will need to restart apache and php

Best regards

**Comment by trasher** [comment]
> Hi,
> Please, could you help me to compile de .mo (I read [this](https://glpi-plugins.readthedocs.io/fr/latest/empty/#compile-mo) ) but I don't have `./vendor/bin/plugin-release` in the directory :-/

Those scripts are not available in plugin releases, you get them when cloning repository only.
As @stonebuzz said, you can just use standard gettext tools.

**Comment by mab18** [comment]
:-) 
I will read yours instructions
Many thanks

**Comment by stonebuzz** [comment]
:+1:
