### ISSUE TITLE
Data Injection PHP error

### ISSUE THREAD

**Issue by newspsoft** [pluginsGLPI/datainjection#188]
Hello,
I have my GLPI server and these are my specs
GLPI 9.4.4
Operating system: CentOS 7
PHP 7.4.0, MariaDB Server 10.4.10-MariaDB, 
datainjection       Version: 2.7.1 
ls -Z /var/www/glpi/plugins/
drwxr-xr-x apache apache ?                                addressing
drwxr-xr-x apache apache ?                                appliances
drwxr-xr-x apache apache ?                                archisw
drwxrwxrwx apache apache ?                                backups
drwxr-xr-x apache apache ?                                dashboard
drwxr-xr-x apache apache ?                                dataflows
drwxr-xr-x apache apache ?                                datainjection
drwxr-xr-x apache apache ?                                fusioninventory
drwxr-xr-x apache apache ?                                invoice
drwxr-xr-x apache apache ?                                manageentities
-rw-r--r-- apache apache ?                                remove.txt
drwxr-xr-x apache apache ?                                reports
And Data Injection PHP error
PHP Notice: Undefined property: PluginDatainjectionBackendcsv::$file in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 200
PHP Warning: fopen(): Filename cannot be empty in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 200
PHP Warning: fread() expects parameter 1 to be resource, bool given in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 205
PHP Warning: fseek() expects parameter 1 to be resource, bool given in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 207
PHP Warning: fgetcsv() expects parameter 1 to be resource, bool given in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 226
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 231
PHP Notice: Trying to access array offset on value of type null in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 232
PHP Warning: fgetcsv() expects parameter 1 to be resource, bool given in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 226
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 231
PHP Notice: Trying to access array offset on value of type null in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 232
PHP Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 217
PHP Notice: Undefined property: PluginDatainjectionBackendcsv::$file in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 245
PHP Warning: unlink(): No such file or directory in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php at line 245

**Comment by stonebuzz** [comment]
Hi @newspsoft 

thanks for feedback

can you test this PR https://github.com/pluginsGLPI/datainjection/pull/189

Best regards

**Comment by newspsoft** [comment]
Hi 
thanks for feedback
I change inc/backend.class.php 
    protected $file = "";
   protected $delimiter;
   protected $encoding;
   protected $errmsg;
   protected $numberOfLines = 0;

And
Fatal error: Access level to PluginDatainjectionBackendcsv::$delimiter must be protected (as in class PluginDatainjectionBackend) or weaker in /var/www/glpi/plugins/datainjection/inc/backendcsv.class.php on line 30

**Comment by stonebuzz** [comment]
Hi @newspsoft 
can you try it again, I updated the PR

**Comment by newspsoft** [comment]
Hi thanks
Its work and inject data, but with PHP Notice:
PHP Notice: Trying to access array offset on value of type bool in /var/www/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 537
PHP Notice: Trying to access array offset on value of type bool in /var/www/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 540
PHP Notice: Trying to access array offset on value of type bool in /var/www/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1511
PHP Notice: Trying to access array offset on value of type bool in /var/www/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1511
PHP Notice: Trying to access array offset on value of type bool in /var/www/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1511
PHP Notice: Trying to access array offset on value of type bool in /var/www/glpi/plugins/datainjection/inc/commoninjectionlib.class.php at line 1511

**Comment by stonebuzz** [comment]
I think it's an another problem about injected fields.
It does not concern the management of the uploaded file (our problem). 

can you open another issue ?

Best regards
