### ISSUE TITLE
import ordinateur avec port réseau

### ISSUE THREAD

**Issue by goupil40** [pluginsGLPI/datainjection#19]
Bonjour,

J'utilise GLPI 9.1 avec DataInjection 2.4.2.
Lors de mon import csv, l'ordinateur est bien ajouté mais pas le port réseau.
J'ai vérifié dans la base de données et il n'y a aucune trace dans glpi_networkports.
Je vous joint mon modèle d'import csv.
![import_pc_macaddress](https://cloud.githubusercontent.com/assets/22907425/19472376/5dcba7f8-9527-11e6-833f-184a45dea976.png)
Est ce un bug de data injection ou moi qui fait mal mon modèle.

Sachant que sur la version 0.85.3 de GLPI, ce même modèle fonctionne.

Merci.

**Comment by trasher** [comment]
Sachant qu'il existe un problème assez conséquent avec le sports réseaux (voir glpi-project/glpi#1178) ; il est tout à fait possible que ce le plugin ne soit pas en cause... 

Ce souci n'est pas encore totalement résolu, ce le sera dans la version 9.1.1 de GLPi.

**Comment by goupil40** [comment]
merci pour ta réponse

**Comment by Slowy** [comment]
j'ai le même soucis ^^

**Comment by trasher** [comment]
Est-ce que ce bogues est reproductible avec la version 9.1.1 de GLPi ?

**Comment by goupil40** [comment]
Bonjour,
j'ai mis à jour mon GLPI en 9.1.1 et je n'ai plus le lien dans outil pour injection de fichiers.
Si je force en mettant l'url des modèles cela ne fonctionne pas.
![datainjection](https://cloud.githubusercontent.com/assets/22907425/21052089/8b4152da-be23-11e6-97d5-0d75a758d09f.png)

**Comment by goupil40** [comment]
mon GLPI est en 9.1.1 et je ne peux plus faire de correspondance dans mon modèle d'import.
Je sélectionne la table et il ne me propose pas de champs.
![datainjection](https://cloud.githubusercontent.com/assets/22907425/21052951/9f275d7c-be27-11e6-9a38-e214979b00da.png)
