### ISSUE TITLE
fatal error : Datainjection with web-applications

### ISSUE THREAD

**Issue by EC2311** [pluginsGLPI/datainjection#190]
Hello

when linking to the fields of web-applications  : fatal error (same for the 2 versions)

GLPI : 9.3.1
Plugin datainjection 2.6.4 
Plugin web-applications 2.5.0 

Fatal error: Uncaught TypeError: Argument 3 passed to PluginDatainjectionCommonInjectionLib::addToSearchOptions() must be an instance of PluginDatainjectionInjectionInterface, instance of PluginWebapplicationsWebapplicationInjection given, called in wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php on line 89 and defined in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php:1967 Stack trace: #(0 wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php(89): PluginDatainjectionCommonInjectionLib::addToSearchOptions(Array, Array, Object(PluginWebapplicationsWebapplicationInjection)) #(1 wwwroot\plugins\datainjection\inc\injectiontype.class.php(204): PluginWebapplicationsWebapplicationInjection->getOptions('PluginWebapplic...') #(2 wwwroot\plugins\datainjection\ajax\dropdownChooseField.php(39): Plu in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php on line 1967

GLPI : 9.4.3
Plugin datainjection: 2.7.0
Plugin web-applications : 2.6.0

Fatal error: Uncaught TypeError: Argument 3 passed to PluginDatainjectionCommonInjectionLib::addToSearchOptions() must be an instance of PluginDatainjectionInjectionInterface, instance of PluginWebapplicationsWebapplicationInjection given, called in wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php on line 89 and defined in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php:1967 Stack trace: #(0 wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php(89): PluginDatainjectionCommonInjectionLib::addToSearchOptions(Array, Array, Object(PluginWebapplicationsWebapplicationInjection)) #(1 wwwroot\plugins\datainjection\inc\injectiontype.class.php(204): PluginWebapplicationsWebapplicationInjection->getOptions('PluginWebapplic...') #(2 wwwroot\plugins\datainjection\ajax\dropdownChoo in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php on line 1967

Due to plugin web-applications ? Or datainjection?
what do you advise ?

Thanks

**Comment by stonebuzz** [comment]
Hi @EC2311 

it's an implementation error from webapplications plugins of datainjection framwork.

You need to open issue to plugn webappliance plugin

herer -> https://github.com/InfotelGLPI/webapplications

Best regards
