### ISSUE TITLE
SQL Error when update changes on user definition

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/datainjection#192]
Hi,

When updating the datainjection of a little file usercode/fistname/name, I see an error in PHP and SQL logs.

For have this error, I have to update the import example file and reassign fields.
(Note the error on other plugin, but it's not dependant, error arrives too when this plugin is disabled, error in created on this plugin, correction is pending)
![image](https://user-images.githubusercontent.com/55535560/75693558-64e14480-5ca7-11ea-8a00-974ba8e591ea.png)

I put nothing on complementary tab, and I just click on "valid the model".

Here are log of SQL : 
```
[2020-03-02 17:02:42] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_datainjection_models` SET `name` = 'import d'utilisateur test' WHERE `id` = '8'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'utilisateur test' WHERE `id` = '8'' at line 1
  Backtrace :
  inc/dbmysql.class.php:948
  inc/commondbtm.class.php:616                       DBmysql->update()
  inc/commondbtm.class.php:1444                      CommonDBTM->updateInDB()
  plugins/datainjection/inc/model.class.php:1251     CommonDBTM->update()
  plugins/datainjection/front/model.form.php:72      PluginDatainjectionModel->switchReadyToUse()
  {"user":"123@srv-glpi-dev"}
```
When I go on tab "correspondances", I have this error in PHP.log
```
[2020-03-02 17:04:12] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): Declaration of PluginAppliancesApplianceInjection::getTable() should be compatible with CommonDBTM::getTable($classname = NULL)
  Backtrace :
  .../appliances/inc/applianceinjection.class.php:39
  inc/autoload.function.php:308                      include_once()
  :                                                  glpi_autoload()
  ...s/datainjection/inc/injectiontype.class.php:138 spl_autoload_call()
  plugins/datainjection/inc/mapping.class.php:138    PluginDatainjectionInjectionType::dropdownLinkedTypes()
  plugins/datainjection/inc/model.class.php:808      PluginDatainjectionMapping::showFormMappings()
  inc/commonglpi.class.php:485                       PluginDatainjectionModel::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"123@srv-glpi-dev"}
```

The PHP error seems to be not dependant of the SQL error : I have the same error on other definitions.
Edit : PHP log context : This error occurs when "correspondances" are set. If no correspondance, no error. I can write another issue if you want, it seems to be two different problems with SQL.

GLPI 9.4.5+Injection 2.7.1

**Comment by mab18** [comment]
When I see the SQL error log, I think the "'" is the source of the problem. ;-)

**Comment by stonebuzz** [comment]
I @mab18 
Yes beacuse your name contain a quote 

can you test this PR -> #193 

Concerning 

```
*** PHP Warning(2): Declaration of PluginAppliancesApplianceInjection::getTable() should be compatible with CommonDBTM::getTable($classname = NULL)
  Backtrace :
```

you need to create issue on appliance plugin repo, it's caused by an bad implementation of core function ```getTable```

Best regards

**Comment by mab18** [comment]
Hi,
The PR corrects the problem ;-) 
I will create an issue for other PHP problem.
Thanks you

**Comment by mab18** [comment]
For info, bug for appliance plugin is here : https://forge.glpi-project.org/issues/5600
