### ISSUE TITLE
Bug avec Numéro de série des badges / Lieu des badges / Sous-Entités

### ISSUE THREAD

**Issue by erik69400** [pluginsGLPI/datainjection#194]
Bonjour,
Je souhaitais importer des badges en masses dans GLPI depuis un CSV mais malheureusement je rencontre des bugs :

- Le numéro de série des badges dans DataInjection ne fonctionne pas (il renvoi vers le nom du badge au lieu du numéro de série. Du coup il m'est impossible d'importer en masse mes badges.
- Le lieu ne fonctionne pas non plus, que ce soit depuis le fichier Excel ou depuis l'interface datainjection en dur.
- La sous-entité ne se met pas à Oui, même si je le configure dans le modèle d'import et directement dans mon import.
![2020-03-09 15_45_53-workplace - HL-017074 - Affichage recherche article _ tiers ect ](https://user-images.githubusercontent.com/33863842/76528919-d83a4180-6471-11ea-86e3-8d004f304988.png)
![2020-03-12 14_51_33-GLPI - Data injection report](https://user-images.githubusercontent.com/33863842/76528923-d8d2d800-6471-11ea-9b6f-e805b52c7099.png)
![2020-03-12 14_52_09-CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US](https://user-images.githubusercontent.com/33863842/76528926-d96b6e80-6471-11ea-8ebb-89c1e687e4ea.png)
![2020-03-12 14_52_23-GLPI - Gestion des modèles - 1](https://user-images.githubusercontent.com/33863842/76528927-d96b6e80-6471-11ea-9037-9524cb3b369e.png)
![2020-03-12 14_52_32-GLPI - Gestion des modèles - 1](https://user-images.githubusercontent.com/33863842/76528928-da040500-6471-11ea-8e58-2593736aa502.png)
![2020-03-12 14_53_14-GLPI - Data injection](https://user-images.githubusercontent.com/33863842/76528929-da040500-6471-11ea-87e7-2f57a3f5f209.png)

**Comment by GuiGuiSoft** [comment]
Bonjour,
J'ai le même problème. Avez-vous trouvé une solution de contournement depuis ?
Cordialement.
