### ISSUE TITLE
Data injection mapping model error codes

### ISSUE THREAD

**Issue by skisking** [pluginsGLPI/datainjection#195]
Hi, I have install glpi 9.4 & add data injection plugin 2.7.1,when I create test model, the headre file name in mapping page display error code like Ãû³Æ... I have capture screen attache it,how to fix that?help

![issue](https://user-images.githubusercontent.com/31581221/78642530-77bde900-78e5-11ea-9a34-e6f14eeaf505.jpg)

**Comment by stonebuzz** [comment]
Can you change fiel encoding when you upload your CSV ?

![image](https://user-images.githubusercontent.com/7335054/78761423-d9806080-7982-11ea-999a-7deaea0675ce.png)


Best regards

**Comment by skisking** [comment]
hi Stanislas,

this issus appear in model management
[cid:e4c9fc38-0d03-4467-8ce7-54e5b87a6120]
________________________________
发件人: Stanislas <notifications@github.com>
发送时间: 2020年4月8日 16:22
收件人: pluginsGLPI/datainjection <datainjection@noreply.github.com>
抄送: skisking <skisking@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pluginsGLPI/datainjection] Data injection mapping model error codes (#195)


Can you change fiel encoding when you upload your CSV ?

[image]<https://user-images.githubusercontent.com/7335054/78761423-d9806080-7982-11ea-999a-7deaea0675ce.png>

Best regards

―

**Comment by stonebuzz** [comment]
Can you post here your CSV file ?

Best regards

**Comment by skisking** [comment]
you can check attachment file, I choose File encoding UTF-8

________________________________
发件人: Stanislas <notifications@github.com>
发送时间: 2020年4月9日 15:59
收件人: pluginsGLPI/datainjection <datainjection@noreply.github.com>
抄送: skisking <skisking@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [pluginsGLPI/datainjection] Data injection mapping model error codes (#195)


Can you post here your CSV file ?

Best regards

―

**Comment by stonebuzz** [comment]
Can you retry with latest version (glpi and datainjection) ? 

Best regards
