### ISSUE TITLE
Datainjection + PHP7.4 = bug

### ISSUE THREAD

**Issue by tofmail** [pluginsGLPI/datainjection#202]
Glpi:9.4.6
plugin:2.7.1
PHP : 7.4
os: ubuntu server 20.04
Hello,

I tried to use data injection for user injection with a.csv file but it seems that the plugin does not allow it.
No error message. And no new user inject

In the debug mod, I have this log:

[log bug datainjection.zip](https://github.com/pluginsGLPI/datainjection/files/4624697/log.bug.datainjection.zip)

Thanks for your help

**Comment by eineLeipzigerin** [comment]
We also have problems with datainjection, PHP Version: 7.2.27 and data injection 2.7.1 ( tried to use data injection 2.7.0, still same problem: nothing was imported.

**Comment by stonebuzz** [comment]
Please see https://github.com/pluginsGLPI/datainjection/issues/188
