### ISSUE TITLE
entities import: impossible to update field

### ISSUE THREAD

**Issue by felag** [pluginsGLPI/datainjection#206]
I use GLPi v9.4.6 and DataInjection v2.7.1.

I cannot **update a field**: for example telephone field.

Here are the steps to reproduce error:

1. Import using following CSV file: [import1.csv.txt](https://github.com/pluginsGLPI/datainjection/files/4803252/import1.csv.txt)

1. Import again using same file, changing phone number.
(For example, changed last digits **89** to **90** : [import2.csv.txt](https://github.com/pluginsGLPI/datainjection/files/4803257/import2.csv.txt)).

There are no errors reported, but there is no change on entity's phone number !

Maybe is it related to #153 ?

Thanks and Regards

**Comment by yokodev** [comment]
Facing Same issue trying to figure out whats the problem

**Comment by cedric-anne** [comment]
Hi all,

#217 should fix this issue. Could you test it ?

Regards
