### ISSUE TITLE
[question] GLPI 9.5 support?

### ISSUE THREAD

**Issue by netgineer** [pluginsGLPI/datainjection#208]
Hey!
So GLPI 9.5 is out and i'm curious will your plugin support new version?
I'm asking cause i'm a new GLPI user with the latest version and now i need to import some CSVs. Of course, i can downgrade to the 9.4 but i'd rather wait if you have plans to add new version support in a couple of weeks.

Thanks.

**Comment by cedric-anne** [comment]
Hi,

GLPI 9.5 compatible version has just been released.

Regards
