### ISSUE TITLE
GLPI 9.5 - Docker - datainjection not enabling

### ISSUE THREAD

**Issue by xventil** [pluginsGLPI/datainjection#209]
i have installed the datainjection plugin but, when i try to activate on setup/plugins, it opens a blank page (front/plugin.form.php) and nothing happens, i have 2 more plugins working great (fusion and forms)

can anyone help me please?

**Comment by cedric-anne** [comment]
Hi,

Can you check GLPI logs ?

Regards

**Comment by xventil** [comment]
here is the result of php-errors.log 

[2020-07-13 15:16:16] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Plugin::getPhpDir() in /var/www/glpi/plugins/datainjection/hook.php at line 49
  Backtrace :
  inc/plugin.class.php:617                           plugin_datainjection_install()
  front/plugin.form.php:47                           Plugin->install()

thank you in advance

**Comment by cedric-anne** [comment]
Which version of GLPI do you use?

**Comment by xventil** [comment]
glpi 9.5 and datainjection  2.8.0

**Comment by cedric-anne** [comment]
Is this the official 9.5.0 version ? How did you installed it ? This method should exists.

**Comment by xventil** [comment]
installed using docker image on hub.docker.com glpi/glpi with a link to mysql docker (mariadb 10.3.23)

php version: 7.4.4

**Comment by cedric-anne** [comment]
This docker image was a test and has not been updated from along time ago. Thus, this image was made to provide a nightly build of GLPI, but is not made to be used in production.
