### ISSUE TITLE
[Data Injection 2.8.0]- soucis import utilisateurs (adresses mail)

### ISSUE THREAD

**Issue by dnaton** [pluginsGLPI/datainjection#210]
Bonjour à tous,

Je suis sous GLPI 9.5.0 avec le plugin Data Injection 2.8.0 et j'ai quelques soucis (mauvaise utilisation ? Bug ?) et j'aimerai avoir un avis.

J'ai créé un modèle, et tout est ok de ce côté

[url=https://zupimages.net/viewer.php?id=20/31/kvot.png][img]https://zupimages.net/up/20/31/kvot.png[/img][/url]
.
.

[url=https://zupimages.net/viewer.php?id=20/31/fja2.png][img]https://zupimages.net/up/20/31/fja2.png[/img][/url]
.
.
Je lance l'import
.
[url=https://zupimages.net/viewer.php?id=20/31/sv8b.png][img]https://zupimages.net/up/20/31/sv8b.png[/img][/url]
.
.
L'import est affiché comme réussi, sans erreurs mais j'ai deux soucis

1) Plusieurs lignes d'erreurs sont affichées
     Notice: Trying to access array offset on value of type bool in C:\xampp747\htdocs\glpi\plugins\datainjection\inc\commoninjectionlib.class.php on line 537
     Notice: Trying to access array offset on value of type bool in C:\xampp747\htdocs\glpi\plugins\datainjection\inc\commoninjectionlib.class.php on line 540
     Notice: Trying to access array offset on value of type bool in C:\xampp747\htdocs\glpi\plugins\datainjection\inc\commoninjectionlib.class.php on line 1511
    
     La troisième ligne est répétée environ 60 fois. PArfois, il y a d'autres n° de lignes qui apparaissent suite à l'import

2) le soucis le plus important : les adresses mails ne sont pas importées :(

J'ai essayé de modifier le choix de l'encodage du fichier sur l'écran d'import (passer de détection automatique à UTF8) mai ça ne change rien :(

Je reproduit le problème à chaque fois, quel que soit le fichier d'import que j'utilise et la manière dont je le crée

Bug ou erreur de ma part quelque part ?

Cordialement,
Damien

**Comment by niroussel** [comment]
Same issue : mail adresses not imported.

GLPI 9.4.5 - Data injection 2.7.1
