### ISSUE TITLE
ERROR MESSAGE : Warning : existing data will be overridden

### ISSUE THREAD

**Issue by talbim** [pluginsGLPI/datainjection#215]
Hi Everyone :)  
I'm using FileInjection for GLPI. I have a problem with the import, when i'm trying to import new laptop on my existing environment, i have this message "Warning : existing data will be overridden" but I just want to add new laptop and not overriden my existing environment

Thnak you

FR : 

Bonjour à tous,

J'utilise Data Injection sur GLPI 9.3.1. Je rencontre un problème lors de l'import de nouveaux laptop. En effet, j'ai un message d'erreur qui me demande d'ecraser l'existant. Ce que je ne veux pas, j'aimerais uniquement ajouter ces nouveaux laptop a mon parc existant. 

Savez-vous comment et si c'est possible de mettre a jour mon parc sans l'écraser ? 

Merci

**Comment by btry** [comment]
Bonjour

Tout d'abord, ce type de question a plus sa place sur le forum de GLPI. Il s'agit d'une aide à l'utilisation.

Quand vous definissez un modèle d'import vous devez choisir une colonne en BDD qui sert de de clé. Celle ci est utilisée pour chercher une entrée qui correspond à la ligne de votre CSV en cours de traitement. Si une correspondance est faite en BDD, cela signifie que votre laptop existe déjà puisque sa clé est delà présente. 

Vous devriez vérifier l'existence de votre laptop avant de retenter l'import, puis prendre une décision. Si le laptop en BDD et celui de votre CSV sont en réalité différents alors vous devriez soit corriger une erreur dans votre inventaire, soit vérifier que votre CSV contient des données  fiables, et le corriger si nécessaire, soit utiliser une autre propriété de vos laptops pour votre clé.

**Comment by talbim** [comment]
Bonjour btry,

Merci pour votre réponse. En effet j'ai posé la question en Janvier  sur le forum de GLPI, mais je n'ai eu aucune réponse des autres utilisateurs. 

La clé est basé sur le numéro de série qui est différent pour chaque laptop. C'est pour ça que je trouve ça bizarre qu'il me demande si je veux écraser les données existante soit si je clique confirmer, tout mes laptop ...

**Comment by btry** [comment]
Pour sécuriser les éléments existant en BDD, vous pouvez modifier votre modèle pour interdire la modification de données, et n'autoriser que des ajouts.

Le numéro de série est une bonne ressource pour le rôle de clé. Vous devriez chercher si un numéro de série de votre CSV est déjà présent en BDD. Si oui, alors il y a probablement une erreur dans le csv ou la BDD. Ça peut être un laoptop qui est présent dans le CVS alors qu'il ne devrait pas, une erreur de saisie dans GLPI ou dans la source d'ou vient votre CSV.

Au pire vous pouvez ignorer les modifications à l'import puis traiter les lignes en erreur dans le rapport produit après l'import fait par data injection.
