### ISSUE TITLE
data injection 2.8.0 CSRF conformity

### ISSUE THREAD

**Issue by appocalyps** [pluginsGLPI/datainjection#218]
Hi i.m using "GLPI 0.90 Copyright (C) 2015 by Teclib' - Copyright (C) 2003-2015 INDEPNET Development Team", i'm trying to install data injection 2.8.0, then in plugins list, data injection is shown as CSRF uncompatible, what could be the problem please !

**Comment by cedric-anne** [comment]
Hi,

GLPI 0.90 is an obsolete version. You should upgrade to 9.5.x, or use datainjection 2.4.x.

Regards
