### ISSUE TITLE
Error Plugins Datainjection

### ISSUE THREAD

**Issue by diegokru** [pluginsGLPI/datainjection#219]
Hi guys
I download a datainjection 2.6.4 an extract to plugins folder. but is not show in the tools o plugins menu.
My glpi version is 9.3.3
![Screen Shot 2020-10-20 at 16 39 25](https://user-images.githubusercontent.com/73200551/96647177-d59aa700-12f2-11eb-9220-017e8732f9f8.png)

please help me!

**Comment by cedric-anne** [comment]
Hi,

GLPI 9.3.x and datainjection 2.6.x are no longer maintained.

Try to logout/login and, if problem persist, ask on [forums](http://forum.glpi-project.org) to get community support.

Regards
