### ISSUE TITLE
Help with data-injection

### ISSUE THREAD

**Issue by libracos** [pluginsGLPI/datainjection#22]
Hello, 
I have a glpi WITHOUT data-injection plugin. I want to install this plugin but I don't find any manual to install it.
I tried to copy all flies of data-injection to glpi directory but it doesn't Works.

Please, 
exist any configuration readme to install this plugin?
exist any standard glpi with data-injection installed?

Regards friends

**Comment by trasher** [comment]
You have to copy the whole `datainjection` directory into the `glpi/plugins` directory.

See https://forge.glpi-project.org/projects/datainjection/wiki/En_manual for (probably out of date) documentation.
