### ISSUE TITLE
error inside the form

### ISSUE THREAD

**Issue by cr1stt0f3r** [pluginsGLPI/datainjection#225]
After installing the 2.8.1 plugin on glpi 9.5.3, an error appears just below the comments field:

Deprecated: Computer_SoftwareVersion has been replaced by Item_SoftwareVersion. in C:\xampp\htdocs\glpi\inc\toolbox.class.php on line 634

Deprecated: Computer_SoftwareLicense has been replaced by Item_SoftwareLicense. in C:\xampp\htdocs\glpi\inc\toolbox.class.php on line 634
![Capturar](https://user-images.githubusercontent.com/26659061/104595308-2f401280-5651-11eb-958e-52ff7a293432.PNG)

**Comment by jbquotient** [comment]
Seconded!  The plugin also does not appear to recognize / split the header columns for mapping -- they're all bundled together as one.

Deprecated: Computer_SoftwareVersion has been replaced by Item_SoftwareVersion. in /htdocs/glpi/inc/toolbox.class.php on line 634
Deprecated: Computer_SoftwareLicense has been replaced by Item_SoftwareLicense. in /htdocs/glpi/inc/toolbox.class.php on line 634


![Screenshot_2021-02-05_10-23-34](https://user-images.githubusercontent.com/7647620/107053239-98bcc800-679c-11eb-8ff2-a1445a2b265a.png)
