### ISSUE TITLE
cant add model

### ISSUE THREAD

**Issue by dmitrycd** [pluginsGLPI/datainjection#227]
I try to add a new model (plugin version 2.7.0), but i get fatal error: 

Fatal error: Uncaught Error: Class 'PluginFields0printerInjection' not found in /var/www/html/glpi/plugins/datainjection/inc/injectiontype.class.php:52 Stack trace: #0 /var/www/html/glpi/plugins/datainjection/inc/injectiontype.class.php(89): PluginDatainjectionInjectionType::getItemtypes(true) #1 /var/www/html/glpi/plugins/datainjection/inc/model.class.php(662): PluginDatainjectionInjectionType::dropdown('', true) #2 /var/www/html/glpi/plugins/datainjection/inc/model.class.php(590): PluginDatainjectionModel->showAdvancedForm('') #3 /var/www/html/glpi/inc/commonglpi.class.php(475): PluginDatainjectionModel->showForm('', Array) #4 /var/www/html/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(PluginDatainjectionModel), 'PluginDatainjec...', '', Array) #5 {main} thrown in /var/www/html/glpi/plugins/datainjection/inc/injectiontype.class.php on line 52

everything worked fine yesterday

![2021-02-10_13-09-59](https://user-images.githubusercontent.com/78850642/107495982-cf7e4e00-6ba1-11eb-9f62-ee7b5a2a15fb.jpg)

**Comment by AnaisMartinez** [comment]
Hi, I´ve the same issue. 
There is an incompatibility between two plugins, in my case fields and data injection. If I deactivate fields, the data injection works. But I need both to work at the same time. Does anyone know how to solve this problem?
