### ISSUE TITLE
Incompatibility between two plugins

### ISSUE THREAD

**Issue by AnaisMartinez** [pluginsGLPI/datainjection#229]
Hi, I´ve an issue.
There is an incompatibility between two plugins, in my case **fields** and **data injection**. If I deactivate fields, the data injection works. But I need both to work at the same time. Does anyone know how to solve this problem?
I'm using:
GLPI 9.5.3 
Fields 1.12.2
Datainjection 2.9.0

**Comment by cconard96** [comment]
Do you have any errors in files/_log/php-errors.log or files/_log/sql-errors.log around the time you experienced the issue?
Is there any other information about the issue you noticed so that I can try recreating the issue?

**Comment by AnaisMartinez** [comment]
I don´t see any erros on the logs. When I activate both plugins, the data injection disable the add icon
