### ISSUE TITLE
Type problem when injecting a network port

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/datainjection#23]
Version of plugin : 2.4.1 and 2.4.1

When injecting an object with a network port, it is not possible to specify the type of the network port.

I would like the network port type to be "NetworkPortAggregate" but the system does not take it into account, It is set to "NetworkPortEthernet" by default. 
Therefore, the function addSpecificNeededFields in the file networkportinjection.class.php : 

```
function addSpecificNeededFields($primary_type,$values) {

      if (isset($values['NetworkPort']['instantiation_type'])) {
         $fields['instantiation_type'] = $values['NetworkPort']['instantiation_type'];
      } else {
         $fields['instantiation_type'] = "NetworkPortEthernet";
      }
      return $fields;
   }
```

NetworkPort is not primary_type

**Comment by abeulink** [comment]
I have this problem too :(
I have a huge list of ChromeBooks with Wifi Mac addresses and tried to import my list in GLPI.
All Wifi Mac Address were imported in Ehternet Mac Addresses instead Wifi Mac Addresses.

And I saw no error messages... 
I used Data Injection plug in version 2.4.2
