### ISSUE TITLE
User field unavailable after GLPI 9.5.5 update

### ISSUE THREAD

**Issue by GuiGuiSoft** [pluginsGLPI/datainjection#233]
Hello,

After GLPI update to 9.5.5 version, the user field is not available anymore.

Example for a computer import, but it also concerns other types of data:  
![image](https://user-images.githubusercontent.com/8069239/115265590-aba62e00-a137-11eb-908a-3e1aeb1085fd.png)

Regards.

**Comment by CIGX1** [comment]
Hello ! 
Same problem here !
It is very annoying :(

**Comment by poupinma** [comment]
Bonjour 
Nous avons le même problème, comment pouvons nous faire pour le resoudre.
cdt

**Comment by Cryy64** [comment]
Hello,

We have a same problem :)

Can do fix it? 👍 

Regards.

**Comment by conchaji** [comment]
Hola!

Mismo problema :-(

Gracias

**Comment by keha35** [comment]
Hello,

The problem come from a modification in the appliance.class.php class in the core of GLPI.
I didn't have time to dig further but if you comment these lines it works as a workaround:
**appliance.class.php lines 442 to 482 :**
`      $tab[] = [
         'id'                 => '1212',
         'table'              => User::getTable(),
         'field'              => 'name',
         'name'               => User::getTypeName(1),
         'forcegroupby'       => true,
         'massiveaction'      => false,
         'datatype'           => 'dropdown',
         'joinparams'         => [
            'beforejoin'         => [
               'table'              => self::getTable(),
               'joinparams'         => [
                  'beforejoin' => [
                     'table'      => Appliance_Item::getTable(),
                     'joinparams' => ['jointype' => 'itemtype_item']
                  ]
               ]
            ]
         ]
      ];

      $tab[] = [
         'id'                 => '1213',
         'table'              => Group::getTable(),
         'field'              => 'name',
         'name'               => Group::getTypeName(1),
         'forcegroupby'       => true,
         'massiveaction'      => false,
         'datatype'           => 'dropdown',
         'joinparams'         => [
            'beforejoin'         => [
               'table'              => self::getTable(),
               'joinparams'         => [
                  'beforejoin' => [
                     'table'      => Appliance_Item::getTable(),
                     'joinparams' => ['jointype' => 'itemtype_item']
                  ]
               ]
            ]
         ]
      ];`

Br.

**Comment by icealin2003** [comment]
@keha35 I tried your solution and it works for now. I hope it doesn't brake anything else ;)
Maybe get's solved in the next version of the datainjection plugin.
Thanks.

**Comment by CIGX1** [comment]
Hello,
I don't find this file, where is it located please ?
I have searched in /var/www/html/glpi/front but I have only this

![files](https://user-images.githubusercontent.com/83716058/142190801-ecfedf0f-264a-4bda-a8d1-bf064a62f9f6.png)

**Comment by keha35** [comment]
Hi it's in var/www/html/glpi/inc/

**Comment by CIGX1** [comment]
> 
> 
> Hi it's in var/www/html/glpi/inc/

Thanks :)

**Comment by TxX8N8LN** [comment]
@keha35 Thanks for your workaround :)

**Comment by cedric-anne** [comment]
Hi,

Could you test #260 ?

Regards

**Comment by TxX8N8LN** [comment]
Hi @cedric-anne ,
i test the commit :
[https://github.com/pluginsGLPI/datainjection/pull/260/commits/0fbf3d13c3f3f4220edb641f1d92cb8204490b6d](url)

It's work for me.
