### ISSUE TITLE
Cannot import Graphic Cards as a component.

### ISSUE THREAD

**Issue by ghost** [pluginsGLPI/datainjection#235]
Hi all,

I'm importing an external db using a csv file. It contains a list of computers with its components (cpu, gpu and memories). I managed to import the computers and assign them the cpu and memories, but I cannot assign the graphic card.

![Screenshot 2021-05-05 at 14 53 05](https://user-images.githubusercontent.com/83711903/117152142-a5f44d80-adb1-11eb-8b85-cb3f5e2034ad.png)

I'm using version data injection plugin v2.9.0 with GLPI 9.5.4.

**Comment by LeonardoSilvaSilva** [comment]
HI Everyone.

I'm facing the same problem of this post author. I went to this #266 post but (and I'm verry sorry for my inability with GLPI) but in all the related posts in #266,  I dindt see any solutions for the problem, only people talking about related issues bu no solution. Can someone help me?
