### ISSUE TITLE
Unable to import network name during computer import

### ISSUE THREAD

**Issue by lorenzo33** [pluginsGLPI/datainjection#240]
Hi everyone,

I want to import all my vm servers with this following fields :

- computer's name
- network name
- domain name (fqdn)
- IP
- Mac
- Network port (PortEthernet)
- PortName : eth
- PortNumber : 0

After import, computers are added successfully but when I'm going to NetworkName Tab, NetworkName, IP Address and FDQN not appear.

During import, I've warning and error : 
PHP Notice (8): Undefined index: id in /var/www/html/glpi/plugins/datainjection/inc/networknameinjection.class.php at line 95
PHP Notice (8): Undefined index: id in /var/www/html/glpi/plugins/datainjection/inc/networknameinjection.class.php at line 95
PHP Warning (2): file_put_contents(/var/www/html/glpi/files/_tmp/11232_results_1626913961.0346): failed to open stream: No such file or directory in /var/www/html/glpi/plugins/datainjection/inc/session.class.php at line 66

Here's my system's setting : 
GLPI 9.5.3 ( => /var/www/html/glpi) Installation mode: TARBALL
Operating system: Linux  RHEL
PHP 7.2.34 : apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) 
Software: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/7.2.34 () 	
Server Version: 10.3.27-MariaDB

**Comment by Mirkk** [comment]
The same issue when trying to import IP addresses seems to persist in the latest GLPI 10.2 with datainjection 2.11.2.
I tried various mappings with NetworkPort, NetworkNames etc. for importing IP Addresses to Computers, no one succeeded. Even one mapping that was successful in GLPI 9.1 does no more work in GLPI 10 (and neither in GLPI 9.5.5).

Can someone give an advice on a correct mapping for adding IP Addresses inside a Network Port in a Computer?
Thank you very much!

**Comment by Mirkk** [comment]
Hi @lorenzo33 did you finally find a possibility to import the network data, and in particular the IP? Thanks!

**Comment by Mirkk** [comment]
I tried for various hours, first with different mapping configurations (remembering, that before 9.1 it worked when filling specific fields for NetworkPort and NetworkName), then by debugging. Without success:

The network port does not get created, thus of course also adding the "NetworkName" with the IP Address fails.
In networkport.class prepareInputForAdd() seems to "destroy" the object. Circumventing this, the NetworkPort gets created, but not linked to the asset, and when creating the "NetworkName", the id of the NetworkPort is missing, what causes the displayed error.  If you are able to create a NetworkName (e.g. with a fake ID in the code), the IP is correctly added (table glpi_ipaddresses). So the only issue seems NetworkPort.

**Comment by Mirkk** [comment]
Hello  @cedric-anne @lorenzo33 ,
I finally found the issue:
Just add to commoninjectionlib.class.php, line #1537 in function effectiveAddOrUpdate:
the part "NetworkPort::getType(),NetworkName::getType()":

 if (
            in_array(get_class($item), [
               Infocom::getType(),**NetworkPort::getType(),NetworkName::getType()**
            ])
            && in_array($key, [
               'items_id',
               'itemtype'
            ])
         ) {
            $toinject[$key] = $value;
         }

Moreover, IP Addresses (aka class NetworkName) are only imported if in the mapping, the first NetworkPort columns are **BEFORE** the first NetworkName columns, e.g. see in this sceenshot:
![image](https://user-images.githubusercontent.com/10242044/183904246-42501854-4412-4e57-b88f-6bc8140b97d4.png)

**Comment by cedric-anne** [comment]
@stonebuzz Could you look at this ?

**Comment by stonebuzz** [comment]
Hi @Mirkk 

can you try this -> https://github.com/pluginsGLPI/datainjection/pull/302

It's a global fix for all objects with ```items_id``` and ```itemtype``` column

Best regards

**Comment by Mirkk** [comment]
Hi @stonebuzz thank you, very elegant, I tested it and can confirm that it works on GLPI10!
I tested it (similarly) also for 2.10.2, the latest datainjection compatible with GLPI 9.x.

The only "unexpected" behaviour that remains, is that the order in CSV and then in the mapping is important to create the NetworkPort before the NetworkName, to import correctly and avoid an error for a missing id. 

Thanks!

**Comment by stonebuzz** [comment]
Great ! 

For "unexpected" behaviour, can you try this -> #303

You need to keep #302

**Comment by Mirkk** [comment]
@stonebuzz Thanks, #302 and #303 are working well. However another issue appears now: The IPs are duplicated at every import, i.e. in glpi_ipaddresses a new (identical) entry is created at every import:
![image](https://user-images.githubusercontent.com/10242044/184105095-ae07bd20-f03b-4d5c-b822-e26c2fd29b0f.png)

**Comment by stonebuzz** [comment]
Hi @Mirkk 
can you try this -> https://github.com/pluginsGLPI/datainjection/pull/304
