### ISSUE TITLE
Cannot map computers.user field 

### ISSUE THREAD

**Issue by rebelx9x** [pluginsGLPI/datainjection#243]
Hello, 
Doing CSV data injection.
Can't map computers.user field because there is no "user" field in drop-down menu.
![user_field-Screenshot 2021-08-26 133337](https://user-images.githubusercontent.com/61737463/130948132-3f790594-87b4-4392-9fb9-02b9200dab57.png)
I can select alternate username, but that's not what I need. I need automatically assign computer I am importing to owner.

Regards

**Comment by TxX8N8LN** [comment]
Hello, show the issues #233

**Comment by cedric-anne** [comment]
Hi,

Could you test #260 ?

Regards

**Comment by TxX8N8LN** [comment]
Hi @cedric-anne ,
i test the commit :
[https://github.com/pluginsGLPI/datainjection/pull/260/commits/0fbf3d13c3f3f4220edb641f1d92cb8204490b6d](url)

It's work for me.
