### ISSUE TITLE
Import asset to multiple Entities

### ISSUE THREAD

**Issue by mrsoliveira** [pluginsGLPI/datainjection#251]
Hi all!
I have made some tests using the plugin Data Injection with Generic Object management.
Both is great option to customize the major object of my desire with GLPi.

I have many clients, with many business units (here Entity).
I Sell our machines and include these on GLPI Asset Management.

Some times, I can made a lot changes in these Assets and Import with data injection directly to wich Entity is apreciated.

To start mi implementation, I imported all machines to "root" entity and move one by one to correct entity.
![Generic_Asset](https://user-images.githubusercontent.com/25850322/138726705-a9d34753-8be2-4e61-8ef1-df60d970ab79.PNG)

**Comment by skreu** [comment]
Hi mrsolevia,

Did you find a solution ?

**Comment by mrsoliveira** [comment]
Good morning!

Unfortunately, I still haven't found a solution to this problem.
