### ISSUE TITLE
Unable to create model and save issue in datainjection-2.9.0

### ISSUE THREAD

**Issue by gopalatvvs** [pluginsGLPI/datainjection#252]
In GLPI-9.5.6. i have installed the plugin is datainjection-2.9.0 . Now i am unable to create the model and save option is not avilable. Could you please look into this issue.

**Comment by derry43** [comment]
I had the same issue and after disabling several other plugins, I found that the Business Process (archibp) plugin by Eric Feron appears to cause some conflicts with the datainjection plugin. Disabling Business Process (archibp) was a workaround for this issue.

**Comment by cconard96** [comment]
Can you check `_files/log/php-errors.log` to see if there were/are any errors when you tried creating the model with the other plugin enabled? The error may tell us if there is a problem here or with the other plugin (more likely). I don't know if `archibp` has an intentional integration with this plugin or not.

**Comment by adul3** [comment]
> Can you check `_files/log/php-errors.log` to see if there were/are any errors when you tried creating the model with the other plugin enabled? The error may tell us if there is a problem here or with the other plugin (more likely). I don't know if `archibp` has an intentional integration with this plugin or not.

Hi
On my GLPI 9.5.7 instance, I installed the datainjection-2.9.0 plugin.
I've the Fieds 1.12.0 installed too.
When the plugin Fields is activated, I can't edit/create any import model for DataInjection.
The import fails with no message returned.
In the `_files/log/php-errors.log` I see this kind of error :
```
[2022-03-15 15:23:36] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFieldsPrinterpolitiqueimpressionInjection' not found in /var/www/assistanceng-dev.univ-lille.fr/htdocs/plugins/datainjection/inc/injectiontype.class.php at line 138
  Backtrace :
  plugins/datainjection/inc/mapping.class.php:138    PluginDatainjectionInjectionType::dropdownLinkedTypes()
  plugins/datainjection/inc/model.class.php:808      PluginDatainjectionMapping::showFormMappings()
  inc/commonglpi.class.php:637                       PluginDatainjectionModel::displayTabContentForItem()
  ajax/common.tabs.php:106                           CommonGLPI::displayStandardTab()
```

**Comment by adul3** [comment]
Sorry for my previous message,

I forgot to `regenerate the blocks` in the Fields plugin configuration, after doing that the datainjector works like a charm !

**Comment by derry43** [comment]
Found the following in the logs with archibp enabled.

```
[2022-03-18 21:08:40] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginArchibpTaskInjection' not found in C:\inetpub\wwwroot\glpi\plugins\datainjection\inc\injectiontype.class.php at line 52
  Backtrace :
  ...ns\datainjection\inc\injectiontype.class.php:89 PluginDatainjectionInjectionType::getItemtypes()
  plugins\datainjection\inc\model.class.php:663      PluginDatainjectionInjectionType::dropdown()
  plugins\datainjection\inc\model.class.php:591      PluginDatainjectionModel->showAdvancedForm()
  inc\commonglpi.class.php:627                       PluginDatainjectionModel->showForm()
  ajax\common.tabs.php:101                           CommonGLPI::displayStandardTab()
```

**Comment by adul3** [comment]
> Found the following in the logs with archibp enabled.
> 
> ```
> [2022-03-18 21:08:40] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginArchibpTaskInjection' not found in C:\inetpub\wwwroot\glpi\plugins\datainjection\inc\injectiontype.class.php at line 52
>   Backtrace :
>   ...ns\datainjection\inc\injectiontype.class.php:89 PluginDatainjectionInjectionType::getItemtypes()
>   plugins\datainjection\inc\model.class.php:663      PluginDatainjectionInjectionType::dropdown()
>   plugins\datainjection\inc\model.class.php:591      PluginDatainjectionModel->showAdvancedForm()
>   inc\commonglpi.class.php:627                       PluginDatainjectionModel->showForm()
>   ajax\common.tabs.php:101                           CommonGLPI::displayStandardTab()
> ```

Hi !
Have you tried to regenerate the blocks ?

**Comment by derry43** [comment]
Yes I regenerated the blocks but this did not fix,

**Comment by derry43** [comment]
Think this my issue is with archibp which does not define the PluginArchibpTaskInjection class
