### ISSUE TITLE
PHP User deprecated function (16384): openArrowMassives() method is deprecated in /var/www/glpi/inc/toolbox.class.php at line 653

### ISSUE THREAD

**Issue by baji03** [pluginsGLPI/datainjection#255]
PHP User deprecated function (16384): openArrowMassives() method is deprecated in /var/www/glpi/inc/toolbox.class.php at line 653

how can i resolve this., 

GLPI 9.5.6 Copyright (C) 2015-2021 Teclib' and contributors

php 7.4

**Comment by trasher** [comment]
Hi,

This is just a warning, an a headache to fix. You should just ignore.

**Comment by baji03** [comment]
Thank you for the response.
