### ISSUE TITLE
 PHP Warning (2): Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Riesuu** [pluginsGLPI/datainjection#256]
Hello,
I have a warning when importing a file, the import goes correctly.

![image](https://user-images.githubusercontent.com/17006344/145989576-c84685c1-f86a-4320-a7a0-7579af6e339b.png)
![image](https://user-images.githubusercontent.com/17006344/145990310-fed5f168-401a-4c73-8c4d-fa39e1931d52.png)

**Comment by cconard96** [comment]
Which version plugin are you using?
