### ISSUE TITLE
'user' field missing from 'computers' table

### ISSUE THREAD

**Issue by landrys6** [pluginsGLPI/datainjection#259]
Unable to map the 'user' field for 'Computers' table after upgrading from GLPI 9.5.4 to GLPI 9.5.5. This also applies to GLPI  9.5.6, 9.5.7 and v10rc1, both for upgrades (with new and existing models), and for new models in clean installs.

**Comment by BWMerlin** [comment]
Same issue here.

**Comment by cedric-anne** [comment]
Hi,

Could you test #260 ?

Regards

**Comment by landrys6** [comment]
Hi Thank you for addressing this issue.  With workaround #260 in place I am now able to update the 'User'  field in both v9.5.7 and v10rc1.  However, While the updates are successful, a number of 'Notice's are output below the results (screenshot attached):
Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 542

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 545

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 1516

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 1516

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 1516

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 1516

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 1516

Notice: Trying to access array offset on value of type bool in E:\Apps\xampp\htdocs\glpi957\plugins\datainjection\inc\commoninjectionlib.class.php on line 1516


![Data injection test #260](https://user-images.githubusercontent.com/99956303/156188823-a38674ac-afcb-4c0b-b94f-610878567b29.png)
