### ISSUE TITLE
Bad computer entity

### ISSUE THREAD

**Issue by nldrsm** [pluginsGLPI/datainjection#262]
Hello,

I'm trying to import computers into a specific entity, for example in sub-entity C which has entity B as its parent, child of entity A

But during the import the computers are always imported in the root entity A.

However, I am well positioned in entity C.

Can you help me ?

GLPI 10.0.0-rc2 

Data Injection 2.10.0-rc2
thank you

**Comment by armanduchi** [comment]
Hello,

Same problem adding assets with a model configured in entities_id=4.

Debug mode shows

PHP User Warning (512): Missing entity ID! in /var/www/html/glpi/src/CommonDBTM.php at line 4314


GLPI 10.0.0-rc2

Data Injection 2.10.0-rc2
thank you

**Comment by stonebuzz** [comment]
Hi @armanduchi, @nldrsm 
can you test this -> https://github.com/pluginsGLPI/datainjection/pull/269

Best regards

**Comment by armanduchi** [comment]
Solved.
Thanks so mouch.
