### ISSUE TITLE
import components - example memory , for stock

### ISSUE THREAD

**Issue by Wolvverine** [pluginsGLPI/datainjection#266]
When trying to create a model for memory card import, there is a problem because not all relevant information can be imported in the model (in total, most of the important information is not possible).
Example:
Name; Model; Type; Serial Number; Size; Invoice; field1 from fields plugin; field2 from fields plugin

It is not possible to map these fields to the appropriate tables. 

There is no access to administrative and financial information. 

Possible to import:
![image](https://user-images.githubusercontent.com/5873929/159295866-cb3341fc-f631-4d32-9cbe-6a6b3789d2ff.png)

not possible to import: 
![image](https://user-images.githubusercontent.com/5873929/159294809-8db27d88-2bee-4701-acee-ab2a8e08a5aa.png)
![image](https://user-images.githubusercontent.com/5873929/159295452-c914cd79-e179-4c59-9749-59e1916595a7.png)

**Comment by Wolvverine** [comment]
Simmilar issue:
https://github.com/pluginsGLPI/datainjection/issues/235
https://github.com/pluginsGLPI/datainjection/issues/249
https://github.com/pluginsGLPI/datainjection/issues/201
https://github.com/pluginsGLPI/datainjection/issues/162
https://github.com/pluginsGLPI/datainjection/issues/137

**Comment by LeonardoSilvaSilva** [comment]
Hi everyone. 

Someone already found a solution for this issue and all the similar ones?
