### ISSUE TITLE
Compatibility with Additional Fields

### ISSUE THREAD

**Issue by armanduchi** [pluginsGLPI/datainjection#268]
Hi,
GLPI 10.0.0-rc3
Data injection 2.11.0-rc1
Additional Fields 1.13.0-rc2

Model to inject fields from additional fields.
SQL error with items_id problem
Table glpi_plugin_fields_printerupcinfos is created, but when we want to import with datainjection a new printer and fill "campus" and "edifici" with new data, following error appears

sql-errors.log:  SQL: INSERT INTO `glpi_plugin_fields_printerupcinfos` (`campusfield`, `datadecomprafield`, `dataaltamantenimentfield`, `databaixamantenimentfield`, `datafinaldegarantiafield`) VALUES ('DNB', '01-02-2004', '2003/10/22', '2013-10-22', '20241022')

If we manually "edit" the additional fields and then "reinject" data, fields are well filled.

Thank you

---------------------------

We have tested in previous versions 
GLPI 9.5.5
AdditionalFields 1.12.9
Data Injection 2.10.0

And the table associated with additional fields glpi_plugin_fields_printerupcinfos
always filled with
items_id = 0

**Comment by cedric-anne** [comment]
Can you provide the corresponding log from php-errors.log ?

**Comment by armanduchi** [comment]
sql-errors.log:  SQL: INSERT INTO `glpi_plugin_fields_printerupcinfos` (`campusfield`, `datadecomprafield`, `dataaltamantenimentfield`, `databaixamantenimentfield`, `datafinaldegarantiafield`) VALUES ('DNA', '21-12-2009', '2001/10/30', '2011-10-30', '2021/10/30')

Table glpi_plugin_fields_printerupcinfos exists , but initially empty
Additional fields we want to add to itemtype printer
campus, datadecompra, dataaltamantniment, databaixamanteniment, datafinaldegarantia

The 2 printers are well inserted in database

The file ware are injecting is simple (printer.csv)

Name;Sn;Campus;DataCompra;Data1;Data2;Data3
printer12;7777;DNA;"21-12-2009";"2001/10/30";"2011-10-30";2021/10/30
printer13;8888;DNB;01-02-2004;2003/10/22;2013-10-22;"20241022"

IMPORTANT NOTE

Once imported the printers, if we manually modify the additional fields THEN

if we try to IMPORT AGAIN the printer.csv file
additional fields ARE UPDATED

**Comment by cedric-anne** [comment]
Can you provide the corresponding log from php-errors.log ?

**Comment by armanduchi** [comment]
[2022-03-25 12:04:55] glpiphplog.WARNING:   *** PHP User Warning (512): Calling isFloat on string in /var/www/html/glpi/src/Toolbox.php at line 3435
  Backtrace :
  src/Toolbox.php:3435                               trigger_error()
  src/Dropdown.php:1681                              Toolbox::isFloat()
  marketplace/datainjection/inc/info.class.php:391   Dropdown::showNumber()
  marketplace/datainjection/inc/info.class.php:306   PluginDatainjectionInfo::showAdditionalInformation()
  marketplace/datainjection/inc/info.class.php:273   PluginDatainjectionInfo::displayAdditionalInformation()
  ...e/datainjection/ajax/dropdownSelectModel.php:52 PluginDatainjectionInfo::showAdditionalInformationsForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.WARNING:   *** PHP User Warning (512): Missing entity ID! in /var/www/html/glpi/src/CommonDBTM.php at line 4339
  Backtrace :
  src/CommonDBTM.php:4339                            trigger_error()
  src/CommonDBTM.php:1273                            CommonDBTM->checkUnicity()
  ...injection/inc/commoninjectionlib.class.php:1539 CommonDBTM->add()
  ...injection/inc/commoninjectionlib.class.php:1453 PluginDatainjectionCommonInjectionLib->effectiveAddOrUpdate()
  ...datainjection/inc/printerinjection.class.php:92 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
  marketplace/datainjection/inc/engine.class.php:147 PluginDatainjectionPrinterInjection->addOrUpdateObject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined variable: entities_id in /var/www/html/glpi/src/CommonDBTM.php at line 4342
  Backtrace :
  src/CommonDBTM.php:1273                            CommonDBTM->checkUnicity()
  ...injection/inc/commoninjectionlib.class.php:1539 CommonDBTM->add()
  ...injection/inc/commoninjectionlib.class.php:1453 PluginDatainjectionCommonInjectionLib->effectiveAddOrUpdate()
  ...datainjection/inc/printerinjection.class.php:92 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
  marketplace/datainjection/inc/engine.class.php:147 PluginDatainjectionPrinterInjection->addOrUpdateObject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /var/www/html/glpi/marketplace/datainjection/inc/engine.class.php at line 195
  Backtrace :
  marketplace/datainjection/inc/engine.class.php:94  PluginDatainjectionEngine->addValueToInject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.WARNING:   *** PHP User Warning (512): Missing entity ID! in /var/www/html/glpi/src/CommonDBTM.php at line 4339
  Backtrace :
  src/CommonDBTM.php:4339                            trigger_error()
  src/CommonDBTM.php:1273                            CommonDBTM->checkUnicity()
  ...injection/inc/commoninjectionlib.class.php:1539 CommonDBTM->add()
  ...injection/inc/commoninjectionlib.class.php:1453 PluginDatainjectionCommonInjectionLib->effectiveAddOrUpdate()
  ...datainjection/inc/printerinjection.class.php:92 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
  marketplace/datainjection/inc/engine.class.php:147 PluginDatainjectionPrinterInjection->addOrUpdateObject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

[2022-03-25 12:05:14] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined variable: entities_id in /var/www/html/glpi/src/CommonDBTM.php at line 4342
  Backtrace :
  src/CommonDBTM.php:1273                            CommonDBTM->checkUnicity()
  ...injection/inc/commoninjectionlib.class.php:1539 CommonDBTM->add()
  ...injection/inc/commoninjectionlib.class.php:1453 PluginDatainjectionCommonInjectionLib->effectiveAddOrUpdate()
  ...datainjection/inc/printerinjection.class.php:92 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
  marketplace/datainjection/inc/engine.class.php:147 PluginDatainjectionPrinterInjection->addOrUpdateObject()
  ...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine()
  ...datainjection/inc/clientinjection.class.php:219 PluginDatainjectionClientInjection::processInjection()
  ...datainjection/front/clientinjection.form.php:40 PluginDatainjectionClientInjection::showInjectionForm()

**Comment by armanduchi** [comment]
Updated to Additional Fields 1.13.0-rc3 and same errors

**Comment by cedric-anne** [comment]
We need to have the stacktrace related to the SQL query you mentionned. Indeed, you just provide a SQL query, but not th corresponding error. Query syntax seems valid, so without the corresponding error message, it is hard to knwo what is the error.

**Comment by armanduchi** [comment]
The SQL error is

SQL Error "1364": Field 'items_id' doesn't have a default value in query "INSERT INTO glpi_plugin_fields_printerupcinfos (campusfield, datadecomprafield, dataaltamantenimentfield, databaixamantenimentfield, datafinaldegarantiafield) VALUES ('DNA', '21-12-2009', '2001/10/30', '2011-10-30', '2021/10/30')"

The table "glpi_plugin_fields_printerupcinfo" is defined but no entry for the new printer i want to add. So there is no "item_id" associated to the new printer.

Whan the new printer is added, i can manually fill the fields of the additional info (in my case upcinfo).
Then in the table there is an entry for the new created item printer.

If we inject the same *.csv file AGAIGN with fields changed to another data , the sql error disappears and the additional fields are update.

SO IMHO, the problem is with NEW ITEMS (Printers, Computer, ....)
... with this new item, there is no data in the tables of additional fields, and when we use DATAINJECTION, new item (printer or computer) is added correctly but FAILS on fields defined in additional fields plugin

**Comment by armanduchi** [comment]
Hi Cedric,

¿ Any suggestions ? ¿ Are you able to reproduce "the scenario" ? ¿ what are we doing wrong ?

Thanks

**Comment by cedric-anne** [comment]
I do not know how to fix this. Plugin code is really obscure to me.

**Comment by armanduchi** [comment]
Hi,

We have tried either with

"Add Tab" or "Insertion in the form (before save button).

In mysql they are defined as "dom" or "tab".


We think the problem is with the table associated 
"glpi_plugin_fields_printerXXXXXX".

The structure is well defined, with the fields we want, but

initially with that table empty , so there is no "items_id" to search for.


Thanks


Same results

**Comment by stonebuzz** [comment]
for this ```fields``` data no injected can you test this -> https://github.com/pluginsGLPI/datainjection/pull/270

maybe https://github.com/pluginsGLPI/datainjection/pull/269 is required

**Comment by armanduchi** [comment]
Wow !!! Yeah !!!

Works great. We could add all types of additional fields (text, datas, 
numerical).

Really we appreciate all your hard work.


Best Regards

**Comment by cedric-anne** [comment]
Fixed by #270
