### ISSUE TITLE
Monitor import / Error on update

### ISSUE THREAD

**Issue by troloff** [pluginsGLPI/datainjection#272]
GLPI 9.5.7 / datainjection 2.10.1

I'm currently testing datainjection for an upcoming import. We used it in previous versions without problems.

When importing monitors using a very simple csv (just 1 line), 
`room;name;8;group;Monitor;M;inventory number`
and mapping like

- 0 -> monitors/location
- 1 -> monitors/user
- 3 -> monitors/group
- 6 -> monitors/inventory number (link field)

new device is added but updating fails with "Injection encounters errors" and error message like this:
![Screenshot 2022-04-08 at 15-05-23 GLPI - Data injection report](https://user-images.githubusercontent.com/25243276/162441535-d7634edd-9da4-486d-a010-0370a7f7d502.png)

Model has set both "Allow lines creation" and "Allow lines update" to "Yes". "Allow creation of dropdowns" and "Allow update of existing fields" is set to "Yes", too.

- is there any way to get more debug output to see what's going wrong here (I checked the logs and enabled debug in web interface, but found nothing suspicious)
- what may cause the update to fail? I am able to modify the newly created monitor through assets->monitors.

Thanks,

**Comment by troloff** [comment]
Found errors in apache logs:

`[Mon Apr 11 15:42:26.835060 2022] [php7:notice] [pid 612199] [client 10.xxx:51640] PHP Notice:  Undefined variable: newID in /var/www/inventory.net.adk.de/marketplace/datainjection/inc/commoninjectionlib.class.php on line 1558, referer: https://inventory.net.adk.de/marketplace/datainjection/front/clientinjection.form.php
[Mon Apr 11 15:42:26.835654 2022] [php7:notice] [pid 612199] [client 10.xxx:51640] PHP Notice:  Undefined variable: newID in /var/www/inventory.net.adk.de/marketplace/datainjection/inc/commoninjectionlib.class.php on line 1559, referer: https://inventory.net.adk.de/marketplace/datainjection/front/clientinjection.form.php
`
This happens every time I try to update an monitor item as described above. Seems like the "update" does not return a newID. But I have no idea where to look why the update fails.

**Comment by stonebuzz** [comment]
Hi @troloff 
can you test this -> https://github.com/pluginsGLPI/datainjection/pull/273 =)

Best regards

**Comment by troloff** [comment]
Hi @stonebuzz,

#273 works for me! Thanks a lot for you help, now we can continue updating our inventory.

Bestm
