### ISSUE TITLE
Compatibilty Fields and data injection

### ISSUE THREAD

**Issue by apprenticeRM** [pluginsGLPI/datainjection#278]
Hello i'm curently working on GLPI and I experience some issues with data injection and fields.
The only way to make injection working is by desactivating the additionals fields plugin. 
The goal is to use data injection with the custom fields.
Is there a fix for this issue ?

There an example of the type of error :
`Uncaught Exception Error: Class 'PluginFieldsMonitormonitorscustomfieldInjection' not found in /var/www/html/glpi/plugins/datainjection/inc/injectiontype.class.php at line 52`

Version :
- GLPI 9.5.7
- Fields 1.12.12
- Data injection 2.10.2

**Comment by sn-bco-2020** [comment]
Same issue with GLPI 10.0.2.
Additional fields injection seems supported when used with new objects (of Objets Management 2.12.1 plugin) and additional fields (plugin 1.17.2). But it ends in error when injection is done for an extension of a core type (tested on computer type and on application/appliance type - new core type of GLPI v10 ) -> injection plugin stays stuck on an error & DataInjection page is blocked (injection cannot be activated any more).
For computer injection, the error received is:
"Uncaught Exception Error: Class 'UNKNOWN' not found in /mnt/diskhome/home/osuspvxn68ue/dbnr4cv8gLM/htdocs/marketplace/datainjection/inc/commoninjectionlib.class.php at line 573"

**Comment by stonebuzz** [comment]
@sn-bco-2020 
can you try this -> https://github.com/glpi-project/glpi/pull/12133
