### ISSUE TITLE
Strange problem installing on GLPI 10.0.2

### ISSUE THREAD

**Issue by paulz1** [pluginsGLPI/datainjection#301]
Trying install datainjection on GLPI 10.0.2

The plugin seems to be ok :
```
define ('PLUGIN_DATAINJECTION_VERSION', '2.11.2');

// Minimal GLPI version, inclusive
define("PLUGIN_DATAINJECTION_MIN_GLPI", "10.0.0");
// Maximum GLPI version, exclusive
define("PLUGIN_DATAINJECTION_MAX_GLPI", "10.0.99");
```

But when try to install it I get :
```
# php bin/console glpi:plugin:install --username=glpi datainjection --force
Traitement du plugin « datainjection »...
Le pré-requis du plugin « datainjection » ne sont pas satisfaits.
Ce plugin requiert GLPI >= 9.5 et < 9.6
```

I think this problem is linked with the old version of "datainjection" that was installed before, but I could not find how to fix the problem.

**Comment by paulz1** [comment]
Solved.

It was the problem with uninstall as I thought.
There was the directory **datainjection** inside of **<GLPI_ROOT>/marketplace** that I didn't see.
Once cleared the new version installed without problem.

P.S. : Why in the documentation we speak about **escalade** ?
```
Move the escalade directory to the <GLPI_ROOT>/plugins directory
```

**Comment by cedric-anne** [comment]
Hi,

Documentation fixed: https://github.com/pluginsGLPI/doc/commit/6df19f89caf3a2fb42f7edf3c29f806aa5d542ba

I close the issue as your problem is now solved.
