### ISSUE TITLE
Call to undefined method Glpi\Toolbox\Sanitizer::dbUnescapeRecursive()

### ISSUE THREAD

**Issue by braghanscathar** [pluginsGLPI/datainjection#319]
Hi 
 glpi 10.0.0.RC3
PHP version (7.4.28)
datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled

I have create a model and run it ans since i've got this error 
Uncaught Exception Error: Call to undefined method Glpi\Toolbox\Sanitizer::dbUnescapeRecursive() in /var/www/html/marketplace/datainjection/inc/commoninjectionlib.class.php at line 1374

each time i go on data injection menu

**Comment by trasher** [comment]
GLPI 10rc3? Are you kidding?

Update to a decent version.

**Comment by braghanscathar** [comment]
I ve update to 10.4 and same issue

**Comment by braghanscathar** [comment]
i'm going to update ato 10.0.5 and updating all plugin and tell you back

**Comment by trasher** [comment]
Method is present since 10.0.0, see https://github.com/glpi-project/glpi/commit/c523fb09a320bd4d50b91c9d124ceb554c63cda0#

**Comment by braghanscathar** [comment]
Hi 

Now with 10.0.5 and 2.12.0 data injection plugin 

Still face issues 
now I've an issue during model creation 
SQL Warnings: 1292: Truncated incorrect DOUBLE value: '' in query "(SELECT `itemtype` FROM `glpi_plugin_datainjection_models` WHERE `id` = '') UNION (SELECT DISTINCT `itemtype` FROM `glpi_plugin_datainjection_mappings` WHERE `models_id` = '') UNION (SELECT DISTINCT `itemtype` FROM `glpi_plugin_datainjection_infos` WHERE `models_id` = '')"
