### ISSUE TITLE
Can't create models

### ISSUE THREAD

**Issue by Tartiflette-glpi** [pluginsGLPI/datainjection#345]
Hi,

I can't create model, the "add" button doesn't appear:

https://ibb.co/HFr3XHX

GLPI 10.0.7
Datainjection 2.13.1 & 2.13.2 (tested both)

Do you have an idea where can be the problem ?

**Comment by sangvt2** [comment]
this is same my problem..

**Comment by grandmok** [comment]
J'ai le même problème également. Le formulaire de création est tronqué. Merci d'apporter un correctif rapidement svp.

**Comment by stonebuzz** [comment]
Hi,
Can you enable debug mode and retry

Can you check  GLPI log file (php, sql)

**Comment by grandmok** [comment]
Hi

here comes the php-errors.log, nothing in sql-errors.log

[2023-10-03 15:43:47] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFieldsPhonebipInjection' not found in /var/www/html/glpi/marketplace/datainjection/inc/injectiontype.class.php at line 52
  Backtrace :
  ...ce/datainjection/inc/injectiontype.class.php:89 PluginDatainjectionInjectionType::getItemtypes()
  marketplace/datainjection/inc/model.class.php:657  PluginDatainjectionInjectionType::dropdown()
  marketplace/datainjection/inc/model.class.php:580  PluginDatainjectionModel->showAdvancedForm()
  src/CommonGLPI.php:676                             PluginDatainjectionModel->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

![image](https://github.com/pluginsGLPI/datainjection/assets/146819768/a2d402ad-c221-46bf-8bb3-01228cd407e5)

Thx

**Comment by stonebuzz** [comment]
related to "fields" plugin
