### ISSUE TITLE
Error: The file could not be found

### ISSUE THREAD

**Issue by simonsbt** [pluginsGLPI/datainjection#357]
I have an error when I try to import a .csv file to inject in a Model, it tells me "The file could not be found" with no more details.

I saw resolved issues about my problem but I can't find the solution

Versions:
Datainjection 2.13.3 & 2.13.2 (Tested on both)
GLPI 10.0.10

**Comment by simonsbt** [comment]
It seems to be related to the file size, the maximum size I was able to import is ~ 2000 Ko

**Comment by stonebuzz** [comment]
Hi @simonsbt 

can you try this -> https://github.com/pluginsGLPI/datainjection/pull/386

**Comment by simonsbt** [comment]
Hi @stonebuzz 

Thank you !
