### ISSUE TITLE
Data injection for cables and sockets

### ISSUE THREAD

**Issue by brunoas** [pluginsGLPI/datainjection#359]
There is no option to inject data for cables and sockets, only for netpoints.

Tried to do a couple updates on hook.php, without success.

**Comment by stonebuzz** [comment]
Hi @brunoas 

the plugin does not currently support ```Socket``` and ```cable``` injection.

it requires quite a lot of work

You can, of course, offer this feature in the form of a PR.

or contact us to develop this feature

Best regards
