### ISSUE TITLE
field "comment" of location entity appended instead of replaced

### ISSUE THREAD

**Issue by ready2play32** [pluginsGLPI/datainjection#369]
Hello, i use GLPI 10.0.10 with the plugin datainjection 2.13.4
I've created a model to import a csv file

The csv file contains locations information and when i update the comment section of the csv and import the file with datainjection plugin , the field comment is appended instead of updating the field

like i import this file

`"id","nom","commentaires"`
`1,toto20,testt`
`2,toto220,test`
`3,toto320,test`

it work the first time when the location doesnt exists but the second time after i update the field comment in csv
the field comment is appended instead of updating

second time file
"id","nom","commentaires"
1,toto20,toto
2,toto220,toto
3,toto320,toto

i have this in comment field 
1 : testttoto
2 : testtoto
3 : testtoto

thx for your help

**Comment by ready2play32** [comment]
I think the problem come from the file inc/commoninjectionlib.php from the function   public function processAddOrUpdate()
Because at the beginning, i though that it was from the file inc/locationinjection.class.php but i tested it  
i added in the function addOrUpdateObject() a print_r like this to print the value before it get added to the database but the value are clean (value are the same that in the csv file and not duplicated)
```function addOrUpdateObject($values = [], $options = []) {


//      echo print_r($values);
//      echo print_r($options);
      $lib = new PluginDatainjectionCommonInjectionLib($this, $values, $options);
      $lib->processAddOrUpdate();
//      echo print_r($lib->getInjectionResults());

      return $lib->getInjectionResults();
   }
```

**Comment by ready2play32** [comment]
Issue solved by removing the line
`$options['displaytype']   = ["multiline_text" => [16]];`
from the locationinjection.class.php


then the field comment is updated and not incremented each time
here the example csv file to set comment with multiple lines
```
"location_name","commentaires"
"toto20","hello
hello2"
"toto220","hello
hello2"
"toto320","hello    
hello2"
```

**Comment by stonebuzz** [comment]
Hi,

This is a "desired" behaviour in the plugin.

Fields of type "multiline_text" are never overwritten

**Comment by ready2play32** [comment]
Hi,
Ok can you confirm that the only way if i want to overwrite multiline text i have to  delete multiline_text of $options['displaytype'] 
and do a csv with line break like this

csv file:
"location_name","commentaires"
"toto20","hello
hello2"
"toto220","hello
hello2"
"toto320","hello    
hello2"

**Comment by stonebuzz** [comment]
Hi @ready2play32 

yes

**Comment by ready2play32** [comment]
Ok @stonebuzz,
Thx
