### ISSUE TITLE
Unable to create the directory /var/www/html/glpi/files/_plugins/datainjection/

### ISSUE THREAD

**Issue by GrnTommi** [pluginsGLPI/datainjection#376]
I moved my 'Files' folder from GLPI to the /var/lib/glpi/ directory, and I'm getting the following error when launching the GLPI page "Unable to create the directory /var/www/html/glpi/files/_plugins/datainjection/" . I couldn't find where the plugin was linking with the 'files' folder. Does anyone have a solution?

**Comment by joschi99** [comment]
Same error, plugin is not working with custom files folder

**Comment by stonebuzz** [comment]
Hi

did you follow this documentation :

https://glpi-install.readthedocs.io/fr/develop/install/index.html#files-and-directories-locations

perhaps the webserver user (e.g. apache) doesn't have rights to the new folder?

**Comment by joschi99** [comment]
rights and configuration are ok, all other plugins and glpi are using the folder under /var/lib/glpi/

**Comment by stonebuzz** [comment]
I don't reproduce, with a ```local_define.php``` as follows, the plugin works correctly

```php
<?php
define('GLPI_VAR_DIR', '/var/lib/glpi');
```

Can you show me your ```local_define.php``` and

as well as the tree structure of your var/lib/glpi

**Comment by joschi99** [comment]
I have done a test on a test environment and found the error, which is related to another plugin. Thank you very much, I will close the case.

**Comment by stonebuzz** [comment]
Can you post here solution? (for @GrnTommi )

Best regards
