### ISSUE TITLE
is this plugin project dead ?

### ISSUE THREAD

**Issue by mathieuchateau** [pluginsGLPI/datainjection#38]
Hello,

I am being worried to see 2 pull requests, 10 issues opened since december without any reply...

is this plugin project dead ? Replies, even if it is only "will be added in next release" would give hope at least.

**Comment by trasher** [comment]
Hello,

Not at all, the plugin is still alive... But we have many things to handle; and not enough time unfortunately.

We're doing our best... Bug triaging is also something that takes time.

Thank you for your comprehension.
