### ISSUE TITLE
Possible bug when restore a dump MySQL

### ISSUE THREAD

**Issue by wanderleihuttel** [pluginsGLPI/datainjection#40]
Hello 

I did a restore a Backup from my GLPI database and after that, the plugin data injection does not show the option in  menu, I need to uninstall and install again for show in the menu.
The problem when I uninstall is that I lost the models saved. 

Best regards
Wanderlei

**Comment by wawax** [comment]
Hello,
Version of glpi and the plugin please ?

**Comment by cedric-anne** [comment]
Hi,

As there is no feedback, I close this issue.

Regards
