### ISSUE TITLE
Import stops after 60 seconds

### ISSUE THREAD

**Issue by joschi99** [pluginsGLPI/datainjection#421]
OS: RHEL 8.10
PHP: 8.2.x
GLPI: 10.0.16
Plugin version: 2.13.5

We try to import a csv file with ~1.500 rows. The import takes more than 60 seconds and stops every time.
![image](https://github.com/user-attachments/assets/088b69e8-608d-4dc7-b960-ecaac666f3ad)

If we split the csv file into smaller pieces with a single import time < 60 seconds then we can import all datas.

I tried to change the max_execution_time=3600 on php, but always the same behaviour. Anyone has a solution?

**Comment by trasher** [comment]
PHP execution time is not the only parameter that should be changed. For example, a timeout also exists on FPM pool when you use php-fpm. It's also a common mistake the changed php configuration file is not the one used by the application.
