### ISSUE TITLE
PHP Notice undefined index field

### ISSUE THREAD

**Issue by ameurou** [pluginsGLPI/datainjection#43]
Hi,

We upgrade from 0.90.5 and 2.4.1 to 9.1.4 and 2.4.2.

Since then, each time we load our template or lauch injection, we got this PHP notice :

`*** PHP Notice(8): Undefined index: field
  Backtrace :
  ...injection\inc\commoninjectionlib.class.php:1925 
  ...atainjection\inc\infocominjection.class.php:115 PluginDatainjectionCommonInjectionLib::addToSearchOptions()
  plugins\datainjection\inc\info.class.php:398       PluginDatainjectionInfocomInjection->getOptions()
  plugins\datainjection\inc\engine.class.php:214     PluginDatainjectionInfo::keepInfo()
  plugins\datainjection\inc\engine.class.php:107     PluginDatainjectionEngine->addAdditionalInformations()
  ...datainjection\inc\clientinjection.class.php:249 PluginDatainjectionEngine->injectLine()
  ...datainjection\inc\clientinjection.class.php:204 PluginDatainjectionClientInjection::processInjection()
  ...datainjection\front\clientinjection.form.php:38 PluginDatainjectionClientInjection::showInjectionForm()`

Here a screenshot on template filed view :

<img width="478" alt="bug" src="https://user-images.githubusercontent.com/11721263/27679414-f66e94bc-5cb8-11e7-9fca-81386c7a58cb.PNG">

Doesn't seems to break the injection, as computers are import with defined fields...

Regards

**Comment by xsgb** [comment]
The same notice is shown there in 9.1.2 with 2.4.2. It's seems to be only displayed for fields coming from the _infocom_ table.

There's my log: https://gist.github.com/xsgb/fa42c5e33075d5b75ba03b7f558da4aa
