### ISSUE TITLE
Problem with Relation fields in Software License Injection

### ISSUE THREAD

**Issue by PlaneNuts** [pluginsGLPI/datainjection#444]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

2.14.0

### Bug description

Note: This was tested on both a brand new install with the above details, as well as on my production environment running GLPI 10.0.15 (same plug-in version, but I did also have this before updating. Unfortunately I didn't note what version I was running befor)

There seems to be an issue in the plugin when trying to inject software licenses. When putting GLPI into debug mode, I see this SQL error. It looks like some of the relation fields are being ignored and the plugin is trying to inject the raw text rather than the ID for the entry from the relation table. 

For computers though, I do see that these relations are being kept. One thing I noticed from the comment in https://github.com/pluginsGLPI/datainjection/pull/389/files was _//CommonDBRelation are managed separately, so related field should be ignored_ and I see
  - `class Computer_Item extends CommonDBRelation` 
  - `class SoftwareLicense extends CommonTreeDropdown`

Is this maybe why this works fine for computers, but not software licenses?

I'm not a dev by any means so I'm not sure how it can be corrected. I'll keep poking through this and see if there anything I more I can find, but if anyone who actually KNOWS what their doing could look at it, it would be greatly appreciated. Feel free to let me know of there is any further detail I can provide.

``` SQL Error "1366": Incorrect integer value: 'Available' for column `glpi`.`glpi_softwarelicenses`.`states_id` at row 1 in query "INSERT INTO `glpi_softwarelicenses` (`name`, `softwarelicenses_id`, `entities_id`, `softwares_id`, `comment`, `number`, `states_id`, `softwarelicensetypes_id`, `users_id`, `serial`, `users_id_tech`, `locations_id`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('Docker Desktop', '0', '0', '1', '', '1', 'Available', '0', 'Test.User', '4', 'Test.User', 'License_Test', '1', 'Docker Desktop', '2024-12-06 18:08:35', '2024-12-06 18:08:35')" ```
![image](https://github.com/user-attachments/assets/997f6523-8667-4b1d-aa0f-b038e252d465)

### Steps To reproduce

Using a CSV mapped to fields with foreign table relations (Location, status, etc. )

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.17 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux Virtual-Machine 6.2.0-35-generic #​35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC
	2 x86_64
PHP 8.1.2-1ubuntu2.19 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at 10.54.9.182 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.18-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.19) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.18) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.17"
GLPI_SCHEMA_VERSION: "10.0.17@bde16719fbd4112f59a9a7d34c66c959bce73434"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	datainjection        Name: Data injection                 Version: 2.14.0     State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by stonebuzz** [comment]
Hi @PlaneNuts 

can you try this https://github.com/pluginsGLPI/datainjection/pull/439 ?

this may help you

**Comment by PlaneNuts** [comment]
Hi @stonebuzz - Changing line 1609 to `if (($option !== false && isset($option['displaytype']) && $option['displaytype'] == 'relation') || !($item instanceof CommonDBRelation)) {` now gives me these two errors

PHP Warning (2): Undefined array key "itemtype" in /var/www/html/glpi/src/Infocom.php at line 282
PHP Warning (2): Undefined array key "items_id" in /var/www/html/glpi/src/Infocom.php at line 282

![image](https://github.com/user-attachments/assets/547a3134-dd17-4980-90b8-4970e308da6f)


This is my field mapping. This is with none of the drop downs currently populated.

![image](https://github.com/user-attachments/assets/dae8a539-bc95-4801-9f54-00982577e77a)

If I remove the links to Financial and Administrative Information I get a message saying the injection was successful, but nothing is actually populated in licenses. I first tried while there were no corresponding entries for the drop downs, and then with populating them manually and trying to import again. Attached is a copy of the sample file I am using for a test import

[Licenses (1).csv](https://github.com/user-attachments/files/18047963/Licenses.1.csv)

**Comment by PlaneNuts** [comment]
So, I've been digging into this a bit, and found that these values that get inserted into the database get set in `getFieldValue()` in commoninjectionlib.class. this seems to be fired before `effectiveAddOrUpdate` mentioned in your suggestion. When I compare trying to inject a software license vs a computer I see the following difference. Going to continue trying to track this down, but if I get stuck figure it would might help someone else

![image](https://github.com/user-attachments/assets/d598c4ec-47d6-4d5d-a55b-1fa913f27123)

**Comment by PlaneNuts** [comment]
@stonebuzz  - Been looking at this, and I'm wondering if this is due to missing displaytype options not being set in the in softwarelicenseinjection.class.php (for this particular case in this issue, there may be more in other contexts. In my case I was just trying to inject licenses). When I compared the computerinjectionclass, it seemed to include all IDs from Computer.php that had datatypes of "dropdown" from rawsearchoptions. 

![image](https://github.com/user-attachments/assets/f14aa6c6-bcab-4fe6-bd1d-a0686ddd1f1c)


So, this is what I have found

When getting to addToSearchOptions, the call to [x]injection.class.php has all ready run setting the keys that should be type "dropdown" (for softwarelicenses this is [5, 6, 7, 110] ). 

Then when addToSeachOptions is called, when it gets to some of these fields that require setting a foreign key, it looks like it's setting the display type as text as it wasn't already set from the injection class

![image](https://github.com/user-attachments/assets/6e94733c-c9a2-490b-9005-1c1da97fb0c5)

After some other magic happens we finally get to setting the final values before getting ready to inject `manageFieldValues` calls `getFieldValue` where there is a switch for displaytype. Since the displaytype is set as text it just keeps the text value rather than going to the "dropdown" case to find the relation value for items like "location" or "status" when calling `setValueForItemtype`

![image](https://github.com/user-attachments/assets/b26c837a-f312-4b32-8fdc-631ecdff6f57)

![image](https://github.com/user-attachments/assets/633d53a4-7787-41c0-b02e-49a0cd52d9b3)

I'm just not sure what these original `$options['displaytype']   = ["dropdown" ...` IDs were populated from, so I don't know if an appropriate fix would be to just add the missing IDs to this array. If that doesn't sound stupid to you, I'll submit a PR for correcting some of these.

**Comment by stonebuzz** [comment]
I reached the same conclusion as you regarding the missing `displaytype` definition for certain `searchOptions`, so your approach is correct.

However, please note two points:  
– Search option with id `80` is blacklisted (see *getBlacklistedOptions()*), because it corresponds to the entity of the item, which is managed by the plugin according to the model’s entity.  
– The search options `160`, `164`, and `110` do not correspond to any search option for *SoftwareLicense*.

```php
php tools/getsearchoptions.php --type=SoftwareLicense
Array
(
    [1] => Characteristics / Name
    [2] => Characteristics / ID
    [3] => Characteristics / Location
    [4] => Characteristics / Number
    [5] => Characteristics / Type
    [6] => Characteristics / Purchase version
    [7] => Characteristics / Version in use
    [8] => Characteristics / Expiration
    [9] => Characteristics / Valid
    [10] => Characteristics / Software
    [11] => Characteristics / Serial number
    [13] => Characteristics / Father
    [16] => Characteristics / Comments
    [24] => Characteristics / Technician in charge of the license
    [25] => Financial and administrative information / Immobilization number
    [26] => Financial and administrative information / Order number
    [27] => Financial and administrative information / Delivery form
    [28] => Financial and administrative information / Invoice number
    [29] => Contracts / Name
    [30] => Contracts / Number
    [31] => Characteristics / Status
    [37] => Financial and administrative information / Date of purchase
    [38] => Financial and administrative information / Startup date
    [49] => Characteristics / Group in charge of the license
    [50] => Financial and administrative information / Budget
    [51] => Financial and administrative information / Warranty duration
    [52] => Financial and administrative information / Warranty information
    [53] => Financial and administrative information / Supplier
    [54] => Financial and administrative information / Value
    [55] => Financial and administrative information / Warranty extension value
    [56] => Financial and administrative information / Amortization duration
    [57] => Financial and administrative information / Amortization type
    [58] => Financial and administrative information / Amortization coefficient
    [59] => Financial and administrative information / Email alarms
    [61] => Characteristics / Template name
    [70] => Characteristics / User
    [71] => Characteristics / Group
    [80] => Characteristics / Entity
    [86] => Characteristics / Child entities
    [91] => Characteristics / Building number
    [92] => Characteristics / Room number
    [93] => Characteristics / Location comments
    [101] => Characteristics / Address
    [102] => Characteristics / Postal code
    [103] => Characteristics / Town
    [104] => Characteristics / State
    [105] => Characteristics / Country
    [119] => Documents / Number of documents
    [120] => Financial and administrative information / Warranty expiration date
    [121] => Characteristics / Creation date
    [122] => Financial and administrative information / Comments on financial and administrative information
    [123] => Financial and administrative information / Start date of warranty
    [124] => Financial and administrative information / Order date
    [125] => Financial and administrative information / Date of last physical inventory
    [129] => Contracts / Type
    [130] => Contracts / Duration
    [131] => Contracts / Periodicity
    [132] => Contracts / Start date
    [133] => Contracts / Account number
    [134] => Contracts / End date
    [135] => Contracts / Notice
    [136] => Contracts / Cost
    [137] => Contracts / Invoice period
    [138] => Contracts / Renewal
    [139] => Contracts / Location
    [142] => Financial and administrative information / Delivery date
    [159] => Financial and administrative information / Decommission date
    [162] => Characteristics / Inventory number
    [163] => Characteristics / Number of installations
    [168] => Characteristics / Allow Over-Quota
    [173] => Financial and administrative information / Business criticity
    [200] => Notes / Notes
    [201] => Notes / Creation date
    [202] => Notes / Writer
    [203] => Notes / Last update
    [204] => Notes / Last updater
    [998] => Characteristics / Latitude
    [999] => Characteristics / Longitude
)
```

**Comment by PlaneNuts** [comment]
Ah, OK. I kept 110 because it was originally there.

160 and 164 are listed in rawSearchOptionsToAdd(), wasn't sure if those should be included too.

Pretty much all of my "programming" experience is from powershell scripts (had to watch a video on how to debug php in VS code over the weekend), so still not 100% sure hour all this works.

I'll remove the options that don't go to anything and submit the PR to close this out. 

Also have an issue when the import also have stuff to add to the infocom, but I'll open a new issue for that and see if I can find what's going on there

**Comment by stonebuzz** [comment]
`rawSearchOptionsToAdd()` is only called to add search option to another object (ex add `SoftwareLicense` dedicated searchoptions to `Software`

![image](https://github.com/user-attachments/assets/8f749692-7f6f-4214-a87b-44df63b1e0c6)

Is not used by `datainjection` =)

Thank you for your contribution

**Comment by PlaneNuts** [comment]
So, as mentioned before, I see the dropdown fields are getting set from the $options that are set in each injection class here 

![image](https://github.com/user-attachments/assets/9f6e5530-c817-458a-98cb-420c4e14d1d4)

But would it make more sense to just set the displaytype for dropdowns like this by using the datatype of the injection class's parent class so if there are any changes in the future, they don't need to be manually added into the injection class?

![image](https://github.com/user-attachments/assets/76c2445a-5aa5-4408-a2b1-5f2b0040c00c)
