### ISSUE TITLE
Injection for 'Domain' Plugin

### ISSUE THREAD

**Issue by Bullot78** [pluginsGLPI/datainjection#46]
Hello,

when i try to create a template to import domains from csv file, there are only those four fields available:
* Comments
* Creation Date
* Name
* Sub-Entity

is there a way to get the other fields such as supplier, expiration date and so on ?

Thank you

**Comment by amma35** [comment]
If this is a problem with the "domain" plugin, you must create an issue in the domain plugin.
Note be careful not to use the "Domain" type of the core and not that of the plugin :  
![datainjection](https://user-images.githubusercontent.com/15138371/40905969-c1906a44-67df-11e8-91be-99052c0a26d0.png)
