### ISSUE TITLE
Data Injection Don´t Work GLPI 9.2.1 Version

### ISSUE THREAD

**Issue by alexlp1982** [pluginsGLPI/datainjection#55]
Greetings,

Someone with the same problem? 

![captura](https://user-images.githubusercontent.com/25614098/34442446-3dd9a8a2-ec90-11e7-80e9-c763df74e634.PNG)

I have the same problem with 2.4.1 and 2.4.2 versions.

The installed version of xampp is:

![image](https://user-images.githubusercontent.com/25614098/34445275-ac820a78-eca0-11e7-8bd4-3e395872bd11.png)

In windows 7 Professional x32.

Regards.

**Comment by trasher** [comment]
Duplicates #47
