### ISSUE TITLE
File not found creating model

### ISSUE THREAD

**Issue by marrobe** [pluginsGLPI/datainjection#60]
Bonjour,
Lors de la création d'un nouveau modèle, le chargement du fichier CSV génère l'erreur "fichier introuvable" 
GLPI 9.2.1 / DataInjection 2.5.0
cdlt

**Comment by phamorais** [comment]
J'ai le même problème

**Comment by dricce** [comment]
Pareil.
Je suis sous Windows / IIS.
GLPI 9.1 / DataInjection 2.4.2: OK.
GLPI 9.2.1 / DataInjection 2.5.0: fichier introuvable.
Je sais que sous LAMP c'est OK aussi dans ces deux configurations, d'après mon fournisseur.

**Comment by chichtacos** [comment]
Hello,

exactly the same issue for me !
Any idea on this toppic ?

Thx !

**Comment by lemkev** [comment]
Bonjour,
Je rencontre le même problème : 
Je suis sous Windows Server 2008 / IIS 7. J'ai fait un CSV de 4 lignes sous UTF-8 (nom, prénom, identifiant, mail).
- Sous une nouvelle installation GLPI 9.1.7 + Data injection 2.4.2 : OK
- Sous une nouvelle installation GLPI 9.2.1 + Data injection 2.5 : Fichier introuvable.

Merci pour votre aide

================================

Hi,
I have the same problem :
I'm using Windows Server 2008 / IIS7. I made a 4 lines - CSV in UTF-8 (last name, first name, ID, mail).
- With a freshly installed GLPI 9.1.7 + Data injection 2.4.2 : OK
- With a freshly installed GLPI 9.2.1 + Data injection 2.5 : File not found

Thanks for your help

**Comment by tsmr** [comment]
inc/model.class.php

l907 - change $temporary_uploaded_filename = stripslashes($_FILES["filename"]["tmp_name"]);

to 

$temporary_uploaded_filename = $_FILES["filename"]["tmp_name"];

(windows files name cannot be C:wamp64tmpphp80A5.tmp)

**Comment by chichtacos** [comment]
Seems to be just fine !
Thx !

**Comment by marrobe** [comment]
Thx ! it's fine

**Comment by dricce** [comment]
same for me, it works! thank you!

**Comment by lemkev** [comment]
Cela marche pour moi aussi, merci beaucoup !
===============
It is working for me too, thanks a lot !

**Comment by supports2l** [comment]
I had the same problem, solved with your solution! 
Thank you!

**Comment by jfsynk** [comment]
Bonjour, 

J'ai exactement le même problème en GLPI 9.2.3, Data injection 2.5.0. Sur un environnement RHEL7.5. Le patch proposé ne résoud pas le problème. 
J'essaye d'uploader un csv hyper simple mais rien a faire : 

![image](https://user-images.githubusercontent.com/39277818/40016662-c6e45600-5802-11e8-9ac1-030081b8a49a.png)


Si vous pouvez m'apporter de l'aide je suis preneur

Merci par avance, 

Cordialement
JF

**Comment by trasher** [comment]
@jfsynk please use english.

**Comment by jfsynk** [comment]
OK sorry,
I've the same issue in environnment GLPI 9.2.3/Datainjection 2.5.0/REL7.5. I try to inject a little CSV file with 2 lines only and the same error appear : the file could not be found. 

Your help will be appreciated

Thanks 
JF

**Comment by jfsynk** [comment]
Hi, anyone have an idea? 

Thks

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/datainjection/commit/7a9fd947146fa1c858639e9cb4ee3e6542f94da9.

**Comment by totalr3call** [comment]
I am having this issue. Using GLPI 9.2.3 and File Injection 2.5.1. Have tried changing every setting available, have modified the csv file every way I can and have only tried 1 row of data. All I get is the File Not Found error.

**Comment by cedric-anne** [comment]
Hi @totalr3call ,

The fix has not been included in a release yet. Can you try after applying this patch https://github.com/pluginsGLPI/datainjection/commit/7a9fd947146fa1c858639e9cb4ee3e6542f94da9 ?

Regards
