### ISSUE TITLE
I do not see the option in mapping to model

### ISSUE THREAD

**Issue by mays1509** [pluginsGLPI/datainjection#61]
It comes out blank and does not give me the option to select the tables and fields.

What could be affecting me?

![imagen](https://user-images.githubusercontent.com/33699462/35876565-07ee4e0a-0b49-11e8-80c8-00e701e2675a.png)

GLPI 9.2.1

**Comment by cedric-anne** [comment]
Hi,

You have to select a file to inject first. Doing this should populate this tab.

Regards.
