### ISSUE TITLE
Issue with GenericObject

### ISSUE THREAD

**Issue by chichtacos** [pluginsGLPI/datainjection#63]
Hi everyone !

I'm using the last versions of these 2 plugins.
Datainjection : 2.5.0
GenericObject 2.5.0
I'm under GLPI version 9.2.1

In datainjection, when I want to create a model with a new type I created with GenericObject (its name is bip), I've got this error on debug mode : 

PHP Warning: Declaration of PluginGenericobjectBipInjection::getTable() should be compatible with CommonDBTM::getTable($classname = NULL) in C:\xampp\htdocs\glpi-test\files\_plugins\genericobject\inc\bipinjection.class.php at line 36

Datainjection works fine with the natives models (computer, phones, etc..)

Thx a lot for your help !

**Comment by trasher** [comment]
Hi,

Your issue seems to be on the genericobject part, not on datainjection one.

**Comment by trasher** [comment]
Thank you :)

**Comment by rafra** [comment]
Hi same problem as chichtacos. After choosing table of new created object and trying to choose field got this error: 
Undefined index: linkfield in glpi\plugins\datainjection\inc\injectiontype.class.php at line 208
Undefined index: linkfield in glpi\plugins\datainjection\inc\injectiontype.class.php at line 215
Undefined index: linkfield in glpi\plugins\datainjection\inc\injectiontype.class.php at line 280

**Comment by trasher** [comment]
This is not the same problem.

**Comment by pVesian** [comment]
It seems this occurs because there is no `linkfield` attribute in most Genericobject fields, so not a Data Injection problem but a Genericobject problem: https://github.com/pluginsGLPI/genericobject/issues/176
