### ISSUE TITLE
The file could not be found (.csv)

### ISSUE THREAD

**Issue by ce3p0** [pluginsGLPI/datainjection#66]
Hi,
I´m new in this forum.
I wanted to learn the GLPI functionality and in addition try to change the content of the inventory (Computer) database fields with the plugin "datainjection".

I downloaded of the newest GLPI version 9.2.1  and installed it on Windows 10. 
The installation of GLPI 9.2.1 was successful and also the installation of the plugin "datainjection" 2.5.0
was no problem.
To test the plugin, I created a .csv file and stored it on the windows desktop. Then I created
a Model for Computer inventory and wanted to open the .csv file (see screenshot below)

![image](https://user-images.githubusercontent.com/37346002/37367081-b6d9288e-2702-11e8-98e0-61005d8ac2d9.png)

After pressing the button "Load this file" I got the error message: "The file could not be found".

Can anybody help what is going wrong her?

Thanks in advance.

**Comment by trasher** [comment]
Hi,

See https://github.com/pluginsGLPI/datainjection/issues/60

**Comment by ce3p0** [comment]
Hi trasher,
my issue is solved, thanks for leading me to #60
