### ISSUE TITLE
Problème de création du modèle

### ISSUE THREAD

**Issue by BZH3529** [pluginsGLPI/datainjection#67]
Bonjour, problème avec la dernière mouture disponible.
Pas de possibilité de création du model alors qu'avec le même fichier sur une version précédent cela fonctionne !
 
Hello, problem with the latest version available.
No possibility of creating the model while with the same file on a previous version it works!

Hola, problema con la última versión disponible.
¡No hay posibilidad de crear el modelo mientras que con el mismo archivo en una versión anterior funciona!

**Comment by cedric-anne** [comment]
Hi,

Can you check if you still have the problem with the current develop branch ? We just fixed some bugs.
If you still have this issue, could you check your logs files and give us more details about the way to reproduce ?

Regards

**Comment by gerald7** [comment]
Bonjour même chose pour moi avec la dernière version.
Impossible de cliquer sur ajouté si on est dans Injection de fichier (+ en gris avec le message : l'ajout est désactivé)

![nonok](https://user-images.githubusercontent.com/39990867/41034744-dd212bac-698a-11e8-87b8-f9b24a41ea73.JPG)


Mais si on va directement dans Gestion des modèles (on peut créer un modèle)
![ok](https://user-images.githubusercontent.com/39990867/41034823-1a0953e6-698b-11e8-8597-d57e60ed8c29.JPG)

**Comment by cedric-anne** [comment]
@gerald7

Links are not correct. I make a PR to fix them (https://github.com/pluginsGLPI/datainjection/issues/90).

However, I still not know what is the issue that @BZH3529 had.

Regards

**Comment by cedric-anne** [comment]
Hi,

We cannot understand the issue due to lack of informations.
If you want to reopen it, please give us more details about your problem.

Regards
