### ISSUE TITLE
Impossible d'installer Datainjection 2.5.0

### ISSUE THREAD

**Issue by Yo93** [pluginsGLPI/datainjection#68]
Bonjour , 
Ayant récemment installé la dernière version de GLPI , j'ai voulu installer la nouvelle version de datainjection mais cela m'indique que l'archive n'est pas de type BZIP.
![image](https://user-images.githubusercontent.com/38653204/39118078-bad70ab8-46e8-11e8-9a81-4f689b04374c.png)
Par contre quand j'installe l'ancienne version (obsolète) cela l'installe sans soucis .
Des idées ?
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

Hello,
I tried to install the datainjection plugin on the last GLPI version but i have the following message who tell me that the archive is not a type of BZIP . 
![image](https://user-images.githubusercontent.com/38653204/39118245-401da8d0-46e9-11e8-8efc-fb594757c23d.png)
Any idea ??

**Comment by trasher** [comment]
Certainly a download issue, I cannot reproduce. Try to download again, and check consistency with GPG.

**Comment by Yo93** [comment]
This doesn't work anyway  i have no issues with the older version but this one i can't use it , always the same message : it's not a bzip file .
