### ISSUE TITLE
[2.5.0] PHP warning messages in the upgrade process

### ISSUE THREAD

**Issue by tabad** [pluginsGLPI/datainjection#70]
# The environment

    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * Source Environment
            * GLPI v9.1.2
                * Data Injection v2.4.2
                * ...and other plugins
        * Target Environment
            * GLPI v9.2.3
                * Data Injection v2.5.0
                * ...and other plugins

# The issue

   When the Data Injection upgrade process from v2.4.2 (GLPI v9.1.2) to v2.5.0 (GLPI v9.2.**3**) starts, it writes the following warning messages into `php-errors.log` file.

> *Note*: The upgrade process from v2.4.2 (GLPI v9.1.2) to v2.5.0 (GLPI v9.2.**2**) was executed successfully.

```text
*** PHP User Warning(512): Table glpi_plugin_data_injection_models does not exists
Backtrace :
:
inc/dbutils.class.php:465 trigger_error()
inc/db.function.php:585 DbUtils->isIndex()
inc/migration.class.php:510 isIndex()
plugins/datainjection/hook.php:214 Migration->addKey()
plugins/datainjection/hook.php:57 plugin_datainjection_migration_24_250()
inc/plugin.class.php:731 plugin_datainjection_install()
front/plugin.form.php:48 Plugin->install()
```

Probably this issue is related with this another one #67.

Regards,

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/datainjection/pull/88 which includes fix made by @amma35 on https://github.com/pluginsGLPI/datainjection/pull/82.
