### ISSUE TITLE
Problème GLPI 0.90 et Injection de fchiers 2.4.1 / Problem GLPI 0.90 and datainjection 2.4.1

### ISSUE THREAD

**Issue by hakim13700** [pluginsGLPI/datainjection#8]
## Nous rencontrons un problème avec le plugin Injection de fichiers. Il est impossible de créer des modèles, je m'explique: lorsque nous arrivons sur le Gestion des modèles pour en créer un nouveau, il est impossible d'accéder à un choix sous la rubrique "Type de données à insérer ", il y a juste le libellé qui apparaît, aucun chamo n'est visible, et donc impossible de générer un modèle et de procéder à un import de fichier CSV. Quand nous désactivons le plugin champs c'est bon. Pouvez vous corriger ce bug pour utiliser ces 2 plugin en même temps. Merci

We encounter a problem with the file Injection plugin. It is impossible to create templates , let me explain: when we arrive on the Template Management to create a new one , it is impossible to access a choice under " Type of data to insert", there just the wording that appears, no chamo is visible, and therefore impossible to generate a template and proceed to a CSV file import . When we disable the plugin fields it is OK.  can You fix this bug to use these two together plugins ? Thanks

**Comment by wawax** [comment]
GLPi version
Datainjection version
Field plugin version

Thank you

**Comment by TICgal** [comment]
Hi,
GLPI 0.90.3
Additionnal fields	0.90-1.2
File injection	2.4.1

Debug mode shows.
```
PHP Notice: Undefined index: itemtype in /var/www/html/glpi/plugins/fields/hook.php at line 252

Fatal error: Class 'PluginFieldsAddtablabelInjection' not found in /var/www/html/glpi/plugins/datainjection/inc/injectiontype.class.php on line 51
```
It looks like an Additional Fields plugin problem:
https://github.com/pluginsGLPI/fields/issues/49

Regards

**Comment by mounia87** [comment]
Hello,

I am having the same issue too.
GLPI: 0.90.3
datainjection: 2.4.1
fields: 0.90-1.2

Is there any solutions for this problem?
Thanks in advance for your help.

Best regards.

**Comment by aldiop** [comment]
HI
is there any solution regarding this issue ?

Thanks

**Comment by hakim13700** [comment]
no 

----- Mail original -----

De: "aldiop" <notifications@github.com> 
À: "pluginsGLPI/datainjection" <datainjection@noreply.github.com> 
Cc: "hakim13700" <hakim.mekadmi@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 8 Septembre 2016 10:57:14 
Objet: Re: [pluginsGLPI/datainjection] Problème GLPI 0.90 et Injection de fchiers 2.4.1 / Problem GLPI 0.90 and datainjection 2.4.1 (#8) 



HI 
is there any solution regarding this issue ? 

Thanks
