### ISSUE TITLE
No button to add template

### ISSUE THREAD

**Issue by GoempieK** [pluginsGLPI/datainjection#9]
When i try to create a new template for file injection there is no button to save.
Glpi version 0.90.5
![image](https://cloud.githubusercontent.com/assets/2872530/17803253/a3d62e00-65f5-11e6-948d-3af4cdfc0041.png)

**Comment by ashmonger** [comment]
Same problem here.

The plugin was working well. I deleted a template and couldn't add a new template after that.
Even after deleting all files from the plugin and tables related directly to the plugin in the database.

![bug_dataing](https://cloud.githubusercontent.com/assets/6398210/17960365/f1e23a08-6aa5-11e6-8d60-88f894802fa3.png)

**Comment by wawax** [comment]
Please switch to debug mode, and report if there's any error being displayed.
I'm also interesting in errors that might appear in the log files.

thank you.

**Comment by ashmonger** [comment]
php-errors.log
>   *** PHP Notice(8): Undefined index: itemtype
>   Backtrace :
>   plugins/fields/hook.php:252
>   :                                                  plugin_datainjection_populate_fields()
>   inc/plugin.class.php:1126                          call_user_func()
>   plugins/datainjection/setup.php:200                Plugin::doHook()
>   ...ns/datainjection/inc/injectiontype.class.php:46 getTypesToInject()
>   ...ns/datainjection/inc/injectiontype.class.php:86 PluginDatainjectionInjectionType::getItemtypes()
>   plugins/datainjection/inc/model.class.php:551      PluginDatainjectionInjectionType::dropdown()
>   plugins/datainjection/inc/model.class.php:499      PluginDatainjectionModel->showAdvancedForm()
>   inc/commonglpi.class.php:464                       PluginDatainjectionModel->showForm()
>   ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()


Nothing in the debug mode of FireFox.

**Comment by ashmonger** [comment]
I just desactivate the Fields plugin and everything is fine now.
There has to be something fishy between the two plugins.

**Comment by wawax** [comment]
hi ashmonger :)

what's the version of the fields plugin ?

**Comment by ashmonger** [comment]
Last one I think. 0.90-1.2

**Comment by glpi-emyy** [comment]
I do not see the problem  between the two plugin it works for a week I'm stuck on it.
