### ISSUE TITLE
Error: The file could not be found

### ISSUE THREAD

**Issue by jaduff** [pluginsGLPI/datainjection#92]
Hi,
I created a new model, and it saved correctly.
Then went to File to Inject, and tried to upload a file.
The interface gives "Error: The file could not be found".
On the server, under glpi/files/_plugins/datainjection a tmp file is created with a size of 0 bytes.

Uploading a document to a ticket works fine, so its not a PHP upload problem as far as I can tell.

FileInjection 2.5.1
GLPI 9.2.3
IIS 7, Windows Server 2012 R2
PHP 7.1.7

Thanks.

**Comment by cedric-anne** [comment]
Hi,

Can you try to test after applying this fix https://github.com/pluginsGLPI/datainjection/commit/7a9fd947146fa1c858639e9cb4ee3e6542f94da9 ?

Regards

**Comment by jaduff** [comment]
Yeah that works, thanks!

**Comment by cedric-anne** [comment]
Same as #60.
