### ISSUE TITLE
data injection process

### ISSUE THREAD

**Issue by wallacengene** [pluginsGLPI/datainjection#93]
Hi,
Im unable to install any of the glpi plugins. When I copy the file to the plugin folder, I cannot add the plugin from setup>plugin. I cannot add or view any plugin, what could I be doing wrong?
The xampp and plugin folder show read only permission and I cannot seem to change the permission.
Please help

**Comment by cedric-anne** [comment]
Hi,

You have to put files of each plugin into a directory having plugins name in the `plugins` directory of GLPI. If you download the plugin as an archive, it has to be uncompressed.

For instance, if you want to install `datainjection` plugin, its files have to be put at the root of `plugins/datainjection` directory.

Regards
