### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kaizerhades** [pluginsGLPI/datainjection#96]
Hi, Guys!

I'm trying to install Data Injection on my GLPI, but I can't due to error below:

- Erro na consulta ao banco de dados: CREATE TABLE IF NOT EXISTS `glpi_plugin_datainjection_models` ( `id` int(11) NOT NULL auto_increment, `name` varchar(255) NOT NULL, `comment` text NULL, `date_mod` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `date_creation` datetime DEFAULT NULL, `filetype` varchar(255) NOT NULL default 'csv', `itemtype` varchar(255) NOT NULL default '', `entities_id` int(11) NOT NULL default '0', `behavior_add` tinyint(1) NOT NULL default '1', `behavior_update` tinyint(1) NOT NULL default '0', `can_add_dropdown` tinyint(1) NOT NULL default '0', `can_overwrite_if_not_empty` int(1) NOT NULL default '1', `is_private` tinyint(1) NOT NULL default '1', `is_recursive` tinyint(1) NOT NULL default '0', `perform_network_connection` tinyint(1) NOT NULL default '0', `users_id` int(11) NOT NULL, `date_format` varchar(11) NOT NULL default 'yyyy-mm-dd', `float_format` tinyint( 1 ) NOT NULL DEFAULT '0', `port_unicity` tinyint( 1 ) NOT NULL DEFAULT '0', `step` int( 11 ) NOT NULL DEFAULT '0', PRIMARY KEY (`id`) ) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_unicode_ci - Erro é Invalid default value for 'date_mod'

I'm using MySQL 5.5

**Comment by trasher** [comment]
see #95
