### ISSUE TITLE
Update of users is broken

### ISSUE THREAD

**Issue by castorsenior** [pluginsGLPI/datainjection#97]
Hello,
I'm using :
- GLPI 9.2.3
- MariaDB 10.1.34
- Data Injection 2.5.2
When I update a user with datainjection, his parameters are then broken when he connects : colors and language in particular (the other menus also are not working anymore, for exemple to view the list of the tickets). Here is a screenshot :
![image](https://user-images.githubusercontent.com/12443836/41592532-2723c2dc-73bd-11e8-99a8-9b0027362bb8.png)
Thank you for your attention and your help !

**Comment by castorsenior** [comment]
Hello, 
New tests today. The situation seems to be better. My previous CSV file was probably corrupted.

**Comment by castorsenior** [comment]
Hello, 
... always broken :-(
Although my CSV file is sure.

**Comment by castorsenior** [comment]
For some users the situation is ok, but for some others the parameters are broken when they connect : colors and language in particular (the other menus also are not working anymore, for exemple to view the list of the tickets).

**Comment by castorsenior** [comment]
To repair, you can use this SQL command :

UPDATE `glpi_users` SET `language` = NULL , `date_format` = NULL ,  `number_format` = NULL , `names_format` = NULL , `csv_delimiter` = NULL , `list_limit` = '20' , `is_ids_visible` = NULL , `use_flat_dropdowntree` = NULL , `show_jobs_at_login` = NULL , `priority_1` = NULL , `priority_2` = NULL , `priority_3` = NULL , `priority_4` = NULL , `priority_5` = NULL , `priority_6` = NULL , `followup_private` = NULL , `task_private` = NULL , `default_requesttypes_id` = NULL , `show_count_on_tabs` = NULL , `refresh_ticket_list` = NULL , `set_default_tech` = NULL , `api_token` = NULL , `display_count_on_home` = NULL , `notification_to_myself` = NULL , `duedateok_color` = NULL , `duedatewarning_color` = NULL , `duedatecritical_color` = NULL , `duedatewarning_less` = NULL , `duedatecritical_less` = NULL , `duedatewarning_unit` = NULL , `duedatecritical_unit` = NULL  , `display_options` = NULL , `pdffont` = NULL , `picture` = NULL , `begin_date` = NULL , `end_date` = NULL , `keep_devices_when_purging_item` = NULL , `privatebookmarkorder` = NULL , `backcreated` = NULL , `task_state` = NULL , `layout` = NULL , `palette` = NULL , `ticket_timeline` = NULL , `ticket_timeline_keep_replaced_tabs` = NULL , `set_default_requester` = NULL , `lock_directunlock_notification` = NULL , `highcontrast_css` = NULL , `sync_field` = NULL WHERE `glpi_users`.`name` LIKE 'misterclark'

**Comment by castorsenior** [comment]
I have done the upgrade to GLPI 9.2.4. The situation is still the same unfortunately.

**Comment by ddurieux** [comment]
I'm checking the code to fix it, we have too the problem
